In [2]:
#Import the needed libraries.
import pandas as pd
import streamlit as st
from rapidfuzz import process, fuzz

In [103]:
#Load the data
df = pd.read_csv('amazon-python.csv')

In [104]:
#Check what columns i have
df.columns

Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link'],
      dtype='str')

In [105]:
#Look at the first 3 rows to verify the data isn't corrupted
df.head(3)

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...

In [106]:
#Replace '_' with a space.
df.columns = df.columns.str.replace('_',' ')

In [107]:
#Convert Columns Titles To Title Case.
df.columns = df.columns.str.title()

In [108]:
#Check the fix
df.columns

Index(['Product Id', 'Product Name', 'Category', 'Discounted Price',
       'Actual Price', 'Discount Percentage', 'Rating', 'Rating Count',
       'About Product', 'User Id', 'User Name', 'Review Id', 'Review Title',
       'Review Content', 'Img Link', 'Product Link'],
      dtype='str')

In [109]:
#List all columns
print(df.columns.tolist())

['Product Id', 'Product Name', 'Category', 'Discounted Price', 'Actual Price', 'Discount Percentage', 'Rating', 'Rating Count', 'About Product', 'User Id', 'User Name', 'Review Id', 'Review Title', 'Review Content', 'Img Link', 'Product Link']

In [110]:
#There are some columns I do not need in my analysis, so I will remove them.

In [111]:
# Drop unneeded columns
columns_to_drop = ['Product Link', 'Img Link', 'Review Content', 'Review Title', 'About Product']
df = df.drop(columns=columns_to_drop)

In [112]:
#Verify the changes
df.columns

Index(['Product Id', 'Product Name', 'Category', 'Discounted Price',
       'Actual Price', 'Discount Percentage', 'Rating', 'Rating Count',
       'User Id', 'User Name', 'Review Id'],
      dtype='str')

In [113]:
# Inspect unique values in 'User Name' to spot placeholders or missing data
print(df['User Name'].value_counts(dropna=False))

User Name
$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger Planet,Justice ⚖️,indrajyoti d.,Aditya Kumar,E.C.GEORGE                                         10
Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jaspreet singh,Khaja moin,Anand,S.ARUMUGAM                                                          8
Satheesh Kadiam,Pritom Chakraborty,Vishwa,Simranpreet Singh,Saptarshi,Amazon Customer,D.RAGHUL,Dharmendra kumar                               8
ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Placeholder,BharanI,sonia,Niam                                                                      7
Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh chouhan,Ravi Siddan,Himanshu Goel,Udaykumar                                                     7
Prashant,Sumesh Sundararajan,Vijay Baitha,S.k nahak,Vikram Kumar,Manish,Jm,amit nayak                                                         6
siddharth patnaik,Dr Sunilkumar H,Krishna,K. S. Rao,vinayp,indhu,Jogi,DRISHTI VASHISTH GUPTA                                                  6
Manoj maddheshiya,Manoj Kumar Sahoo,Saumil s.,Jean-Louis M.,Mahesh,syed azhar abbas,prabakaran,Sidhu                                          5
Ayush,ROHIT A.,Kedar,Haran,Santosh Ghante,KRISHNENDU,Harindra,sangamesh                                                                       5
Placeholder,श्रीPKजी,Gauri salkar,aQeel,Ashish Raj Arora,Ankit,Amazon Customer,Ramamoorthy Jaykumar                                           5
Wraith,Krishna Engineering,Kindle Customer,Deeps,Chintada Bhaskar Rao,FH,Vasudev,Done Chandra Mouli                                           5
Actual user,Shanti lal Gurjar,Gowthami,Amrut K.,chetan tandel,Mwnzil brahma,Amazon Customer,Karthik                                           5
venkatesh kg,Raghuram,YOGESH,Manan Parmar,Nikunj .R. kukadiya,Shivansh Sharma,KAPIL NIMKER,Suriya                                             5
AV,Mathan kumar,Amol Manjrekar,Suraj_nirmalkar,ASIF ANSARI,Jugalkishor yadav,Chinmayee Ninawe,Samba Shiva                                     5
Jayesh,Rajesh k.,Soopy,amazon customer,Aman,Shankar,dinesh,Chitra,Ajaybabu.O.M                                                                4
Pavan A H,Jayesh bagad,Shridhar,rajendran,karuppu k,Akshay wani,Abbimaniu Singh,VISHAL H BADSHE                                               4
Rishav Gossain,Shashank Mallamraju,Purnendu,gunasekaran desomayananam,Anto RK,Sukrit Basak,Manoj Kumar,Sethuram.S                             4
GHOST,Amazon Customer,A Vase,Mani Jha,Anu B,Ganesh Inguva,Prabhu,Amazon Customer                                                              4
Binu,Sabjan,Ramkapil,User,Amazon Customer,ganesh,basavaraj huggi,Mangesh Borkar                                                               4
prateeq,Suraj Chand,viswanath Raju,Ramamoorthy,Nitesh singh,Adnan,Kailash,Chandani Dinodia                                                    4
Vijayan C V,Sanjay P.,keshav,Dharemesh K.,Amazon Customer,Rajesh,Sagar Yadav,Vaibhav                                                          4
sameer Dubey,virender,Amazon Customer,Jay,Siddharth,Kaveri Pramod,Ravinder yadav,RAKESH SWAIN                                                 4
yogita ratre,Arun k.,Amol Basutkar,janarthanan,Naman,keshav Chelmeti,Hritik jain,Jatin Shah                                                   4
virender malhotra,Vikas kabra,Das,Naveen,Amazon Customer,Adv. Manish kotwani,Vinod Jadhao,Priti tijare                                        4
Rahul Singh Rauthan,Sanjoy C,Prashanthi,Aditya Singh,Satyajit Patale,Owais,Amazon Customer,Himon Roy                                          4
Roshan Renji Cherian,SivavaraprasadPV,Kranthi,A K Bindhani,pravesh,Subrat,Max,JAWAGAR T                                                       4
Meghnad,Partha Dey,JAIDEV CHOUDHARY,Mayank Singh,JeneZ,chetan kamerkar,Gangadhar                                                              4
Kunal,Himanshu,viswanath,sai niharka,saqib malik,Aashiq,Ramu Challa,Sanjay gupta                                                              3
rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK,Bhargav,Durai Vignesh,Amazon Customer                                                          3
Vivek kumar,Amazon Customer,SARTHAK,Chiranjeevi,V V GIRI KUMAR,Rajnandini,Akshay Talla,sudhanshu chaubey                                      3
Azhar JuMan,Anirudh Sood,Hari Krishnan PS,Akash Jindal,PRADEEP,Rajesh,Divya Kothari,abhijit                                                   3
Tanya,Anu,Akshay,Vishal Sagara Shetty,Swatilekha Sarkar,Jithindas,IBRAHIM S,Sundaram J.                                                       3
Priya,Mansi,Plaban,Vivek,Taufique Ahmed,Praveen kumar,Robbin,arjun sharma                                                                     3
Deepaak Singh,siva k.,MUNDATH BALGOPAL,BOOPATHI,Rakesh,Ana,Xolo,Rushi                                                                         3
Birendra ku Dash,Aditya Gupta,Abdulla A N,Deepak,Gowtham,Rakesh,Pawan Kumar,Prabhat Raj Pathak                                                3
Prasannavijayaraghavan G.,Preet Sikka,Theeban Raj,Nishikant,Gurpreet S.,Manoj,SP,Ashutosh                                                     3
Rahman Ali,MARIYA DASS,Md Aftab,roshan s.,Mohan,Devendu Sawant,Shek hussain,Prathap Pathaneni                                                 3
Yashpreet Singh,Abiram,Aakaash Ramchandani,Amit katoch,Avijit Basak,Anirban B.,Dass,Gopalakrishnan                                            3
ATHARVA BONDRE,Sujitkumar Thorat,Chandrasekara rajasekara reddy,J vasanth,Placeholder,roshan,Boopathi,Rajesh                                  3
Amazon Customer,Govind Gujarathi,Vihari,shalem,Tejas,RADHA krishanan,Vasudeva Govindraju,Amazon Customer                                      3
Pravin Kumar,Maestrov,rag,Mukundha2good,Amazon_Shopper,Sonic,Pratap,Amazon Customer                                                           3
Pratyush Pahuja,Thiyagarajan,yeses,Amazon Customer,Ajinkya,The Scarred Man,KULDEEP GUPTA,Abhishek Thapar                                      3
Neeraj Vishwakarma,Siddharth,SD1908,Mukundha2good,manjunath h,Vidhi Nigam,Amazon Customer,Tarun Gupta                                         3
Anonymous,Sugam Agrawal,Diganta Gogoi,Amazon Customer,Saigal84,Sonal ashish,Arbind Kumar,Neeraj yadav                                         3
Arun verma,Arv,Aashna Nasta,Harshitha,Sunny Panchal,Snigdha Mallik,None_123,Ravindra J.                                                       3
pruthvi natraj,Phani,Amazon Customer,TechDevoteeIndia,Devanand S B,Anuradha Banerjee,xxxxxxxxxxxxxxxxxxxxxx,chintan                           3
harpreet,Y Kiran Korneli Reddy,Kadir,SP,Mr Sab.,Rupesh Singh,Abdul Maktedar,Anshita                                                           3
Hremant,Anjaneyulu,Madhav,NOTTADRIS,Deepak,P,M.SASIKUMAR,S.Suresh                                                                             3
livin sebi,Anand k.,Rahul Pandita,Fazil Mohamed,Steve,Shivasunhith,Varun Kumar,Advaid Haridas                                                 3
Gopal krishna rout,Customer,Amazon Customer,AMAN KUMAR,Amazon Customer,Ghanshyam Hemade,Satyam Pandey,Amazon Customer                         3
Sunil Funde,Biju Abraham Thomas,Samir,Rahul Sharma,Avninder Singh,Tribhuvan more,N Patel,Bhavy kachhadiya                                     3
Mahesh Paryani,Tejas Panchal,SUBHASH,Kushagra Saxena,Masthan,Dipak Sutrdhar,Nitin,pushkraj_4_ever                                             3
Vaishnavi,Rahul meja,Talo Mosuom,Subodh kumar,Sayan Bhowmick,Mayank Singh Solanki,Nagendran,Kiran Garud                                       3
ASR,Amazon user,Rama Rao,Vinay,ANIKET,NAGA SHANKAR.K,pawan k.,Ravi                                                                            3
Prasad Pavithran,Mahesh Chandra K M,Pannalal singroli,vinod thonti,Mayank Dunkwal,swarn,Rekha H gohil,Vaibhav Sharma                          3
Sunny J.,Praveen Pavitrhran,nitesh,Yadav,vansh gurjar,Krishna,Pantiphun Gonmei,Santosh Panhale                                                3
Vishnu VP,P S Agarwal,Rajesh Kumar,RAMA,Vaibhav saxena,Venu Singani,V Arumugaperumal,HariBol ❤                                                3
Mahantesh,Gaurav Chaubey,uma vijay,Asif ikbal,Lomish Kumar,Kavya Singh,Sagar Mahata,Meherunnesha Sarkar                                       3
tarun kumar,mahesh radheshyam tawari,Blackspade,Manoj Kumar,Kartik Sharma,Placeholder,Arun,Yuvashree                                          3
Atulya Sinha,SujayZ™️☑️                                                                                                                       3
Amazon Customer,Soham Dere,Amazon Customer,kumar Raja D,Gopal kumar,Chandra kant,Nijamuddin Kuraisi,Shankar                                   3
Vineet,shreyas,Amazon Customer,shaurya,Kartik Yadav                                                                                           3
Indro,Bhavesh Bodat,Amazon Customer,Ambalika Sarkar,Bhosale Techno Solution Pvt Ltd,Agnish Mallick,Radhika Arumugam,Krishna                   3
Samar Kumar Das,Jamshed,Jitendra Prajapati,Om Parkash Gagneja,Pavitra S,Dona Sreekumar,Souryajit Swain,Shreevathsa NC                         3
Thukkaram,Vishnu,Vyshnav g nair,Vijaya lakshmi,Dileepkumar,AJAY KUMAR,Amit sahu,Amazon Customer                                               3
anurag,Nirmal Singh,Vikas Keshavrao Vanave,K. Sarath,Abid Hossain,Mahesh Kumar,Amazon Customer,Vinay Kumar Sadhula                            3
Sneha Suyal,Maheswaran,Vamsi Mohan,CK,arya,Nisha,CSK_OFFICIAL,hiba                                                                            3
Santosh Kumar,Prateek Jain,shubham,Ahsan Shaikh,Munish waran,Lalitaroat060682@gmail.co,Nancy Arulraj,Nevil Gandhi                             3
Kapil kumar,Rajendra K Jadhav,Nazaf beg,Jose Febin,suresh gaur,Rinku Barota,Jagdish Joshi,8826277722                                          3
NIRMAL.N,Manoj kumar,SOMNATH DAS,Harsha,Pradhut Roy,MAHENDRA NATH DAS,Naveen Kumar,Gopi Sahu                                                  2
aditya d.,Paranthaman,ashik rahman c,Rajas c.,Madan Tejaswi,Sumit,chaitanya srikrishna,subeh sharma                                           2
Anand sarma,lokeshnist,C,SAI KIRAN,Amazon Customer,Jagdeesh singh,Kalpit Sultania,gopi                                                        2
Rishabh,Amazon Customer,Darpan chauhan,Kumar Ketan,Amazon Customer,jayaprathap,Nirmal,Mihul pandey                                            2
Verified Buyer,Avishek Majumdar,Drowna roy,mahaboobali khan,Aamir,PRAHLADAN K N,Abdulkadir,raja                                               2
Anmol,Vani,Tejas Jha,Rishabh Gupta,Nik,Harsha,Thota Srinivas,Lokesh                                                                           2
Abhishek Kumar,Arun prasath,Naveen,Harmit,Placeholder,Precision Engineering,Senthil Kumar B,Sasikumar madurai                                 2
Koushal K Jain,Mathew Jibin,Jeevan,Hemanth J.,Rajiv krishna,Mohammad Thayub Pasha,MANOHAR MALTHANE,pragati                                    2
Shiva,Uzef,kottala samuel,Renjith,Dhivakaran,Mark,Utkarsh Tripathi,Vijay Sreekantan                                                           2
Paul Joe,Simon Rex P. J.,Santhosh,Rajat Singh 2,Placeholder,Jay,VARUN PANDEY,Jai Jyothir                                                      2
Amazon Customer,DHONDU,Saurabh,Promod George,Ramesh Haran,mram,Placeholder,SHASHANK                                                           2
nilesh,EAGLE,Manoj KNS,Titus P.,Paras singla,arun,Ankur Awasthi,BALASUNDHARAM B                                                               2
Amazon Customer,Yousuf,Raja Laxman,Pooja Thapa,Selva Vellingiri A,Nikhil Padwal,Bipin,sandip                                                  2
Vipan Agnihotri,Hitender singh,Anuj Chauhan,Mufti Abul Hasan,Amazon Customer,MDR,Jai kumar,Rohan Wakade                                       2
nisar,Pralipta Kumar Sahoo,Vimal kumar g s,Amazon Customer,Amazon Customer,Amith Kumar M,Ekant Sharma,K R S                                   2
Arun S.,Jeevan Prasad,mitesh,Tasmai Agrawal,Parvathi,Mohammadnaeem Surajwala,Suriya,Amazon Customer                                           2
Thenmozhi,manish,Brajesh Jha,sushil kumar,Prasanth,Vishal Mehra,LmcX,Prashant Parkhe                                                          2
Ravi Shankar,Prakash Luhariya,bhavesh sabalpara,Anup Roy,Hasibul seikh,Manoj Kumar,Amazon Customer,DEEPAK  MAZUMDAR                           2
Satyanarayana,mohd irfan,Pankaj,Shirish Shivarkar,Thomas,datta DG,NB SHOP,Vijay                                                               2
Vinay,Amazon Customer,Naveenkumar Vemula,sumit,Ajay,vivek rajpooot,drravish,8309-873146                                                       2
𝕵𝖆𝖙𝖎𝖓 𝕮𝖍𝖆𝖉𝖍𝖆,palpandia153,Arvind,Nithyadhakshina,Basha_Neerati,shaker,Amazon Customer,D Ravi                                                  2
Nadhiyarasan,Saurabh Aggarwal,Dibya,Sai Sriya,Sayed,Bhupendra Verma,Yash suhagiya,Manuj Patel                                                 2
SQL,ARUN KUMAR,veer,Ravi shankar,Shivam Kumar,ramesh,Bibin,Hem Roy                                                                            2
MOINUL H.,Jayendra Pai,Avinash kumar,Sreekanth,Piojeet,simam.mular,Sagar,Saumik Shashwat                                                      2
Kiran Kolla,Vishal gupta,Pranav,JS,Palak dadhich,8360101472,Pravin,Rahul M.                                                                   2
Pratik,Amazon Customer,Abhishek,Derrick Angelsz,Prakhar gupta,Harshal Mehta,Bhanu Vardhan,Rajesh                                              2
UtdBuzz,Mukund Nagvenkar,S.R K.,Pruthvi Raj Goud                                                                                              2
Ganesh,P P.,anas,Dr G S Santosh,Amit Benwal,jaswant sai,Vinod Gahlot,Piyush Handa                                                             2
Raj Mohammed,Samson,Haroon sayeed,P Imran Khan,Manohar P,SRF Prashant,Akash Sharma,Sumesh                                                     2
Abhay Goyal,Apurva,Shilpa,Vishnu Narayanan,Kushagra S.,Rogin Cherian,Amazon Customer,Jay d.                                                   2
Mahender Singh,Vinay,Supratim Banerjee,Vinod Bhattu,Amitabha,RISHAV RAJ,khushal027,Shubham Gupta                                              2
SMG,Rohit,roy,Sukumar Ballavolu,Jeeva,Sirajdurvesh,Adhikundhan,Manjit Kaur                                                                    2
Moon Tej,Aditya sikarwar,P kanaka raju,Ajay,Pramod K.,Lalpi Sektak,RAM JI GUPTA,Siva                                                          2
Soumya R.,sivaramakrishnan c,shradha nair,Mohammed Rameezuddin,AR,Vivek,Riyas R.,Amazon Customer                                              2
Gaurab Chakraborty,Pratik Patel,Rahul sharma,SEKAR,Nilesh Madhani,Saurabh Dongre,s s.,Sumit jogade                                            2
samarth shukla,Sanjeev Kumar,Gigi,G RAJAN,Srinu Jonnada,Ezaz Ashraf,Subhasisha B.,sudhansu sekhar khandai                                     2
VM,Dilip,The Mango Couple,Jogendra,Shashi Kumar,Ryan,Kannan,Santhosh                                                                          2
Rashmi,Raghvendra,Hari Prasad P,Vishnu singh,Tarun Kumar Sharma,Dharmendra,K j suresh,Mahore.lakhan                                           2
Anubhab,Himanshu Yogi,Amit,Chandra sekhar sahoo,ArdKn,Devesh,Yasoob Rizvi,Abeendranath K.                                                     2
Princey,Subodh Gupta,Amazon Customer,Ram Sarikh,A R,SUMEDH RANVIR,ankit dalal,Subramanyam                                                     2
Mahesh savale,Sameer Mandal,Sree ram vasanthada,Pulak ray,Abhishek Chauhan,Bsharat Ali,vipin gupta,Bunty s                                    2
Uzair Drabu,Ravindra Sistu,Pranav Dhumal,Amresh singh,Palash Gandhi,Verified Customer,Anudeepika Ankam,karan                                  2
Sumit Nath,Aneesh Mohan,Yogesh Badekar,Manisha,Nishtha Goel,Sanjay,RAJINDER SINGH,Priyanka Chowdhury                                          2
Rakesh Roshan,Kani,Amazon Customer,Amazon Customer,Cheekoti Rameshwara murthy,MBS GOLD JEWELLERS,Durvesh Sawant,Wilson Rodrigues              2
Ranjitha Parida,Shubham Pawar,Arul,Lokesh K V,Nandita Talukdar,Sushma Pradhan,Vaibhav S,Amazon Customer                                       2
Deepankar G.,Babu Singh Rathore,Liton Das,Biswajit Udayabhanu,Anil p.,Anoop Sharma,Rameshwar Singh Rathore,Palash Santra                      2
Chandra.g,Shan Mohd,Suvajit Thakura,Radhe,Jyoti,Amazon Customer,kajal Kiran,Arun                                                              2
Andy,Deepak Karki,B J SHIVA SHANKAR,Shakil A.,Vikas Jeughale,Priti raut,Vikas,Amit T.                                                         2
Shekhar Badola,Pravin,Kishor,Ananta Bhaskar Somawanshi,Anonymous,Jyothi,Rishi,Amazon Customer                                                 2
Soumendra Pattanayak,Kumar.katukuri,RAJULAPATI MARUTHI VARA PRASAD RAO,Souvik,Mahendran G,It's Me Swaraj ...,Vijay prajapati,Dewang           2
Jayesh,Rajesh k.,Soopy,amazon customer,Aman,Shankar,Ajaybabu.O.M,dinesh,Chitra                                                                2
Diamond heart,Amazon Customer,Pritish Biswas,Sriram Ramanathan,Srinivasan Subramanian,zubair,Amazon Customer,Amit Chotrani                    2
RAMKISAN,Pawan Kumar yadav,Nikhil,Drew Arsenic,nisar,kanishk,Amazon Customer,Kulveer Singh                                                    2
Vikrant,Ganesh Gholap,⚡ Pushpendra Singh Patel ⚡,Gaurav,sumegh,Jigar,Dhruba Jyoti Das,Anjeela                                                 2
archit,Arjun Sen,Divya Devkar,User,Vaishnavi Sonker,Santhosh,Sai raj,Mohammed.afsar                                                           2
Velir,Dileep Venigalla,chakrapani p,kuldip teli,Shanky,Rama,Saurabh Srivastava,Vineeth G                                                      2
Ajit Kumar Rai,chetan tandel,Tanankirambabu,Mohammed amaan,ashish bajaj,SUMIT KUJUR,Yajnesh,Raj Kishor Singh                                  2
Rajasekhar,Dimpal,rajat kumar,akanksha,Noone,Hemavaraprasad,Sachin Katyal,BUNGA DINESH                                                        2
Ishwar Singh Sankhla,sai k.,Prathmesh Acharekar,T-y,Jasmin Gosrani,Pankaj,Mahesh,Muzafar                                                      2
App,Dr. Rinchin,Priyanka Devaraj,Yasinlove,Anand Patel,bhaskar,MUHAMMAD ALAU DIN,Mantu kumar Sahoo                                            2
Ranit Barman,Ravi Singh,Karan Rai,Amazon Customer,Saurabh,Jayesh,Amol kale,Sankar Prasad Dutta                                                2
Anirban,Abhi Khaire,Sachin,Tanisha bhoir,Jitendra vishwakarma,Archana,NILESH,Ajay                                                             2
Shaik John Saida,Nilay Kambli,Amazon Customer,Harsh Kumar Shrivastava,Tamzid Hasa Dipu,Yatin,Arty,Anoop Chandran                              2
Kindle Customer,Arun Kalkunte,Amit Kumar,Dhanush,Shiva sai,Moumita Bhanja,Nagaraj S H,Maneesh Mathew                                          2
Gojo Satoru,NOORUL RILWAN,hrithik,satyanarayana,Tanishq,Debasish Saha,Anu Manoj,Prasad                                                        2
Vishal shah,Sameer,Joshilla P.,Sunil Govind Jawale,Pawan kumar,C.Rajeshkannan,Manisha tyagi,Wizzy                                             2
Bristidev Burman,P VENKATESH,D.Dutta,Swapnil Patil,ABHAY SINGH,Rohit,Manikanta,D MANJUNATHAN                                                  2
shiv,Pankaj Bhatt,Dipanshu Kr Biswas,Jeet Jangam,Ekta,subhabrata paul,Anurag kumar,Manish B.                                                  2
Sagar,Shreyas,Arjun Thomas,Sachin Yadav,Karthikeya Reddy,Raja,Anku kumar,Sagar kate                                                           2

In [114]:
#cells aren't single names — 
#they're comma-jammed blobs like:"Amazon Customer,Sethu madhav,Akash Thakur"

In [115]:
#I need to show all the rows instead of a sample of them.
pd.set_option('display.max_rows',None)

In [117]:
# Verify the changes
#I want to see all the names separately, each name on its own line
all_names = df['User Name'].dropna().astype(str).str.split(',').explode().str.strip()
names = all_names.value_counts(dropna=False).head(300)
for name in names.index:
    print(name)

Amazon Customer
Placeholder
Kindle Customer
Rajesh
Deepak
Rohit
Arun
Prashant
Amit
Anand
Manoj Kumar
Vivek
Aditya Kumar
Karthik
Krishna
Sethu madhav
E.C.GEORGE
Ankit
Abhishek
Manav
ArdKn
Shankar
Rakesh
Mahesh
$@|\|TO$|-|
Akash Thakur
Burger Planet
Justice ⚖️
indrajyoti d.
Ajay
Pankaj
Manish
S.ARUMUGAM
Akshay
Santhosh
Jay
Customer
User
Pradeep
Vinay
Rahul
Ravi
Sameer
Adarsh gupta
Sundeep
S.Sayeed Ahmed
jaspreet singh
Khaja moin
Himanshu
JD
Jayesh
Aman
Priya
Ashutosh
Mohan
Naveen
Siddharth
Anonymous
Vijay
Nitin
Satheesh Kadiam
Pritom Chakraborty
Vishwa
Simranpreet Singh
Saptarshi
D.RAGHUL
Dharmendra kumar
Nirbhay kumar
Sagar Viswanathan
Asp
BharanI
sonia
Niam
Omkar dhale
HEMALATHA
Ajwadh a.
amar singh chouhan
Ravi Siddan
Himanshu Goel
Udaykumar
Harsha
Ayush
Neeraj Vishwakarma
Suriya
Ganesh
Amrut K.
chetan tandel
Pranav
AV
indhu
Gaurav
Sunil
Rajesh k.
Soopy
amazon customer
dinesh
Chitra
Ajaybabu.O.M
Manoj
SP
Sumit
Mukundha2good
Shiva
arun
Gowthami
Mwnzil brahma
Pratik
Unknown
Vishal
YOGESH
ASIF ANSARI
Sumesh Sundararajan
Vijay Baitha
S.k nahak
Vikram Kumar
Jm
amit nayak
siddharth patnaik
Dr Sunilkumar H
K. S. Rao
vinayp
Jogi
DRISHTI VASHISTH GUPTA
Nikhil
Prasad
Ashish
Vivek kumar
Shridhar
Anu
Praveen kumar
Manoj maddheshiya
Manoj Kumar Sahoo
Saumil s.
Jean-Louis M.
syed azhar abbas
prabakaran
Sidhu
ROHIT A.
Kedar
Haran
Santosh Ghante
KRISHNENDU
Harindra
sangamesh
GHOST
A Vase
Mani Jha
Anu B
Ganesh Inguva
Prabhu
श्रीPKजी
Gauri salkar
aQeel
Ashish Raj Arora
Ramamoorthy Jaykumar
Wraith
Krishna Engineering
Deeps
Chintada Bhaskar Rao
FH
Vasudev
Done Chandra Mouli
Saurabh
Ramamoorthy
Nitesh singh
Adnan
Kailash
Vaibhav
Actual user
Shanti lal Gurjar
Santosh
Rahul Sharma
Sagar
Raj
Satish
Vikas
Priyanka
Srinivas
Prakash
Amit Kumar
venkatesh kg
Raghuram
Manan Parmar
Nikunj .R. kukadiya
Shivansh Sharma
KAPIL NIMKER
Mathan kumar
Amol Manjrekar
Suraj_nirmalkar
Jugalkishor yadav
Chinmayee Ninawe
Samba Shiva
Vaishnavi
Vikas kabra
Amazon customer
Arul
Lokesh K V
Anil
Gangadhar
Nisha
Ahsan Shaikh
Aniket
Sandeep
Kunal
Aashiq
Durai Vignesh
Chiranjeevi
Pavan A H
Jayesh bagad
rajendran
karuppu k
Akshay wani
Abbimaniu Singh
VISHAL H BADSHE
PRADEEP
Tanya
Rishav Gossain
Shashank Mallamraju
Purnendu
gunasekaran desomayananam
Anto RK
Sukrit Basak
Sethuram.S
Pawan Kumar
Manoj kumar
Naveen Kumar
Abiram
Aakaash Ramchandani
Anirban B.
Boopathi
Tejas
Sonic
Ajinkya
Abhishek Kumar
Tarun Gupta
Saigal84
Arv
nisar
Binu
Sabjan
Ramkapil
ganesh
basavaraj huggi
Mangesh Borkar
Anshita
prateeq
Suraj Chand
viswanath Raju
Chandani Dinodia
Madhav
P
Vijayan C V
Sanjay P.
keshav
Dharemesh K.
Sagar Yadav
Arvind
Samir
Avninder Singh
Pavan
Anuj
Pravin
sameer Dubey
virender
Kaveri Pramod
Ravinder yadav
RAKESH SWAIN
Shubham Gupta
ASR
AR
Shubham
Ram
Bhanu
Deepak Kumar
Raja
Yash
Ramesh
Akash
CK
venkatesh
madhu
yogita ratre
Arun k.
Amol Basutkar
janarthanan
Naman
keshav Chelmeti
Hritik jain
Jatin Shah
Manisha
Sanjay
virender malhotra
Das
Adv. Manish kotwani
Vinod Jadhao
Priti tijare
Prasad Pavithran
Mahesh Chandra K M
Pannalal singroli
vinod thonti

In [118]:
# Replace missing or generic user names with 'N/A' while keeping valid names unchanged.
df['User Name'] = df['User Name'].apply(
    lambda x: 'N/A' if pd.isna(x) or str(x).strip().lower() in[
        'placeholder',
        'amazon customer',
        'kindle customer',
        'unknown',
        ''
    ]else x
)

In [119]:
# Verify the changes
all_names = df['User Name'].dropna().astype(str).str.split(',').explode().str.strip()
names = all_names.value_counts(dropna=False).head(300)
for name in names.index:
    print(name)

Amazon Customer
Placeholder
Kindle Customer
Rajesh
Deepak
Rohit
Arun
Prashant
Amit
Anand
Manoj Kumar
Vivek
Aditya Kumar
Karthik
Krishna
Sethu madhav
E.C.GEORGE
Ankit
Abhishek
Manav
ArdKn
Shankar
Rakesh
Mahesh
$@|\|TO$|-|
Akash Thakur
Burger Planet
Justice ⚖️
indrajyoti d.
Ajay
Pankaj
Manish
S.ARUMUGAM
Akshay
Santhosh
Jay
Customer
User
Pradeep
Vinay
Rahul
Ravi
Sameer
Adarsh gupta
Sundeep
S.Sayeed Ahmed
jaspreet singh
Khaja moin
Himanshu
JD
Jayesh
Aman
Priya
Ashutosh
Mohan
Naveen
Siddharth
Anonymous
Vijay
Nitin
Satheesh Kadiam
Pritom Chakraborty
Vishwa
Simranpreet Singh
Saptarshi
D.RAGHUL
Dharmendra kumar
Nirbhay kumar
Sagar Viswanathan
Asp
BharanI
sonia
Niam
Omkar dhale
HEMALATHA
Ajwadh a.
amar singh chouhan
Ravi Siddan
Himanshu Goel
Udaykumar
Harsha
Ayush
Neeraj Vishwakarma
Suriya
Ganesh
Amrut K.
chetan tandel
Pranav
AV
indhu
Gaurav
Sunil
Rajesh k.
Soopy
amazon customer
dinesh
Chitra
Ajaybabu.O.M
Manoj
SP
Sumit
Mukundha2good
Shiva
arun
Gowthami
Mwnzil brahma
Pratik
Unknown
Vishal
YOGESH
ASIF ANSARI
Sumesh Sundararajan
Vijay Baitha
S.k nahak
Vikram Kumar
Jm
amit nayak
siddharth patnaik
Dr Sunilkumar H
K. S. Rao
vinayp
Jogi
DRISHTI VASHISTH GUPTA
Nikhil
Prasad
Ashish
Vivek kumar
Shridhar
Anu
Praveen kumar
Manoj maddheshiya
Manoj Kumar Sahoo
Saumil s.
Jean-Louis M.
syed azhar abbas
prabakaran
Sidhu
ROHIT A.
Kedar
Haran
Santosh Ghante
KRISHNENDU
Harindra
sangamesh
GHOST
A Vase
Mani Jha
Anu B
Ganesh Inguva
Prabhu
श्रीPKजी
Gauri salkar
aQeel
Ashish Raj Arora
Ramamoorthy Jaykumar
Wraith
Krishna Engineering
Deeps
Chintada Bhaskar Rao
FH
Vasudev
Done Chandra Mouli
Saurabh
Ramamoorthy
Nitesh singh
Adnan
Kailash
Vaibhav
Actual user
Shanti lal Gurjar
Santosh
Rahul Sharma
Sagar
Raj
Satish
Vikas
Priyanka
Srinivas
Prakash
Amit Kumar
venkatesh kg
Raghuram
Manan Parmar
Nikunj .R. kukadiya
Shivansh Sharma
KAPIL NIMKER
Mathan kumar
Amol Manjrekar
Suraj_nirmalkar
Jugalkishor yadav
Chinmayee Ninawe
Samba Shiva
Vaishnavi
Vikas kabra
Amazon customer
Arul
Lokesh K V
Anil
Gangadhar
Nisha
Ahsan Shaikh
Aniket
Sandeep
Kunal
Aashiq
Durai Vignesh
Chiranjeevi
Pavan A H
Jayesh bagad
rajendran
karuppu k
Akshay wani
Abbimaniu Singh
VISHAL H BADSHE
PRADEEP
Tanya
Rishav Gossain
Shashank Mallamraju
Purnendu
gunasekaran desomayananam
Anto RK
Sukrit Basak
Sethuram.S
Pawan Kumar
Manoj kumar
Naveen Kumar
Abiram
Aakaash Ramchandani
Anirban B.
Boopathi
Tejas
Sonic
Ajinkya
Abhishek Kumar
Tarun Gupta
Saigal84
Arv
nisar
Binu
Sabjan
Ramkapil
ganesh
basavaraj huggi
Mangesh Borkar
Anshita
prateeq
Suraj Chand
viswanath Raju
Chandani Dinodia
Madhav
P
Vijayan C V
Sanjay P.
keshav
Dharemesh K.
Sagar Yadav
Arvind
Samir
Avninder Singh
Pavan
Anuj
Pravin
sameer Dubey
virender
Kaveri Pramod
Ravinder yadav
RAKESH SWAIN
Shubham Gupta
ASR
AR
Shubham
Ram
Bhanu
Deepak Kumar
Raja
Yash
Ramesh
Akash
CK
venkatesh
madhu
yogita ratre
Arun k.
Amol Basutkar
janarthanan
Naman
keshav Chelmeti
Hritik jain
Jatin Shah
Manisha
Sanjay
virender malhotra
Das
Adv. Manish kotwani
Vinod Jadhao
Priti tijare
Prasad Pavithran
Mahesh Chandra K M
Pannalal singroli
vinod thonti

In [120]:
# df['User Name'] = df['User Name'].apply(
#     lambda x: 'N/A' if pd.isna(x) or str(x).strip().lower() in[
#         'placeholder',
#         'amazon customer',
#         'kindle customer',
#         'unknown',
#         ''
#     ]else x
# )
#The code does not work. There is something wrong with it!
#The Names did not change after I checked them.
#The likely cause: The User Name
#cells aren't single names — 
#they're comma-jammed blobs like:"Amazon Customer,Sethu madhav,Akash Thakur"

In [121]:
#Want to confirm this is the problem:
#If this returns 0 (or a suspiciously low number) 
#even though i know "Amazon Customer" appears in the data, 
#that confirms exact whole-cell matching is the blocker.
contains=df['User Name'].astype(str).str.strip().str.lower().str.contains('amazon customer').sum()
equal=df['User Name'].astype(str).str.strip().str.lower().eq('amazon customer').sum()
print(f'contains = {contains} and equal = {equal}')

contains = 529 and equal = 0

In [122]:
#As I expected, 
#the problem is that the User Name column cells aren't single names
#— they're comma-jammed blobs.

In [123]:
#I need to clean the data at the individual-name level,
#not the cell level, using the explode() approach.
generic_terms = ['placeholder', 'amazon customer', 'kindle customer', 'unknown', '']
def clean_names(cell):
    if pd.isna(cell):
        #Step 1: if the whole cell is empty/missing, just return 'N/A'
        return 'N/A'
    #Split the cell into individual names using the comma
    names_list = str(cell).split(',')
    #Go through each name one by one and check it
    cleaned_list=[]
    for name in names_list:
        #Remove extra spaces 
        name = name.strip()
        #lowercase version for comparison
        name_lower = name.casefold()

        if name_lower in generic_terms:
            # Replace generic name
            cleaned_list.append('N/A')
        else:
            # Keep the real name
            cleaned_list.append(name)
    #Join the cleaned names back together with commas
    return ','.join(cleaned_list)

df['User Name'] = df['User Name'].apply(clean_names)

In [151]:
# Verify the changes
# all_names = df['User Name'].dropna().astype(str).str.split(',').explode().str.strip()
# names = all_names.value_counts(dropna=False).head(300)
# for name in names.index:
#     print(name)
# contains=df['User Name'].astype(str).str.strip().str.lower().str.contains('amazon customer').sum()
# equal=df['User Name'].astype(str).str.strip().str.lower().eq('amazon customer').sum()
# print(f'contains = {contains} and equal = {equal}')
# contains=df['User Name'].astype(str).str.strip().str.lower().str.contains('amazon customer').sum()
# equal=df['User Name'].astype(str).str.strip().str.lower().eq('amazon customer').sum()
# print(f'contains = {contains} and equal = {equal}')
# df.loc[
#     df['User Name'].astype(str).str.strip().str.lower().str.contains('amazon customer'),
#     'User Name'
# ]
#pd.set_option('display.max_colwidth', None)
#pd.set_option('display.max_columns', None)
# df['User Name'] = df['User Name'].str.replace(
#     'Amazon Customercare',
#     'N/A',
#     case=False,
#     regex=False
# )
# df['User Name'] = df['User Name'].str.replace(
#     'BOSSAmazon Customer',
#     'N/A',
#     case=False,
#     regex=False
# )
# 
#After all the checks, the adjustments are done, so let's go to the next step.

In [160]:
df.to_csv('amazon-python.csv', index=False,encoding='utf-8-sig')

In [167]:
#Look at the Actual Price and Discounted Price values and their data types
print(df[['Actual Price','Discounted Price']].head())
print(df[['Actual Price', 'Discounted Price']].dtypes)

  Actual Price Discounted Price
0       ₹1,099             ₹399
1         ₹349             ₹199
2       ₹1,899             ₹199
3         ₹699             ₹329
4         ₹399             ₹154
Actual Price        str
Discounted Price    str
dtype: object

In [168]:
for col in ['Actual Price','Discounted Price']:
    # Remove the symbol and commas
    df[col] = df[col].str.replace('₹', '').str.replace(',', '')
    # Convert to numeric
    df[col] = pd.to_numeric(df[col])

In [169]:
# Verify the fix (they should now be float64)
print(df[['Actual Price', 'Discounted Price']].dtypes)

Actual Price        float64
Discounted Price    float64
dtype: object

In [173]:
# Verify the fix (Remove the symbol and commas)
print(df[['Actual Price','Discounted Price']].head())

   Actual Price  Discounted Price
0        1099.0             399.0
1         349.0             199.0
2        1899.0             199.0
3         699.0             329.0
4         399.0             154.0

In [176]:
#Look at the raw format of the Category column.
#I noticed that it contains a long chain of categories separated by a pipe symbol (|).
# Look at the raw format of the Category column
print(df['Category'].head())

0    Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables
1    Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables
2    Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables
3    Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables
4    Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables
Name: Category, dtype: str

In [177]:
#I will use the str.split() function to break that long text apart at every | symbol.
#Then, I will keep only the first two parts and rename them to Category and Sub Category.
# Split the text into multiple columns based on the '|' delimiter
#expand=True tells Pandas to put the split results into separate columns.
split_cat = df['Category'].str.split('|',expand=True)
# Keep the first part (index 0) as Category
df['Category'] = split_cat[0]
# Keep the second part (index 1) as Sub Category
df['Sub Category'] = split_cat[1]

In [179]:
# Verify the split worked cleanly
print(df[['Category', 'Sub Category']].head(3))

                Category             Sub Category
0  Computers&Accessories  Accessories&Peripherals
1  Computers&Accessories  Accessories&Peripherals
2  Computers&Accessories  Accessories&Peripherals

In [181]:
#All columns for now.
df.columns

Index(['Product Id', 'Product Name', 'Category', 'Discounted Price',
       'Actual Price', 'Discount Percentage', 'Rating', 'Rating Count',
       'User Id', 'User Name', 'Review Id', 'Sub Category'],
      dtype='str')

In [183]:
df.to_csv('amazon-python.csv',index=False,encoding='utf-8-sig')

In [195]:
# Look for messy spacing in product names
df['Product Name'].head(100).tolist()

['Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)',
 'Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)',
 'Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices',
 'boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)',
 'Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)',
 'pTron Solero TB301 3A Type-C Data and Fast Charging Cable, Made in India, 480Mbps Data Sync, Strong and Durable 1.5-Meter Nylon Braided USB Cable for Type-C Devices for Charging Adapter (Black)',
 'boAt Micro USB 55 Tangle-free, Sturdy Micro USB Cable with 3A Fast Charging & 480mbps Data Transmission (Black)',
 'MI Usb Type-C Cable Smartphone (Black)',
 'TP-Link USB WiFi Adapter for PC(TL-WN725N), N150 Wireless Network Adapter for Desktop - Nano Size WiFi Dongle Compatible with Windows 11/10/7/8/8.1/XP/ Mac OS 10.9-10.15 Linux Kernel 2.6.18-4.4.3',
 'Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Micro USB Cable for Smartphones, Tablets, Laptops & Other Micro USB Devices, 480Mbps Data Sync, Quick Charge 3.0 (RCM15, Black)',
 'Portronics Konnect L POR-1081 Fast Charging 3A Type-C Cable 1.2Meter with Charge & Sync Function for All Type-C Devices (Grey)',
 'boAt Rugged v3 Extra Tough Unbreakable Braided Micro USB Cable 1.5 Meter (Black)',
 'AmazonBasics Flexible Premium HDMI Cable (Black, 4K@60Hz, 18Gbps), 3-Foot',
 'Portronics Konnect CL 20W POR-1067 Type-C to 8 Pin USB 1.2M Cable with Power Delivery & 3A Quick Charge Support, Nylon Braided for All Type-C and 8 Pin Devices, Green',
 'Portronics Konnect L 1.2M POR-1401 Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function (White)',
 'MI Braided USB Type-C Cable for Charging Adapter (Red)',
 'MI 80 cm (32 inches) 5A Series HD Ready Smart Android LED TV L32M7-5AIN (Black)',
 'Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C to Type C Cable for Smartphones, Tablets, Laptops & Other Type C Devices, PD Technology, 480Mbps Data Sync (RCTT15, Black)',
 'boAt Type C A325 Tangle-free, Sturdy Type C Cable with 3A Rapid Charging & 480mbps Data Transmission(Black)',
 'LG 80 cm (32 inches) HD Ready Smart LED TV 32LM563BPTC (Dark Iron Gray)',
 'Duracell USB Lightning Apple Certified (Mfi) Braided Sync & Charge Cable For Iphone, Ipad And Ipod. Fast Charging Lightning Cable, 3.9 Feet (1.2M) - Black',
 'tizum HDMI to VGA Adapter Cable 1080P for Projector, Computer, Laptop, TV, Projectors & TV',
 'Samsung 80 cm (32 Inches) Wondertainment Series HD Ready LED Smart TV UA32T4340BKXXL (Glossy Black)',
 'Flix Micro Usb Cable For Smartphone (Black)',
 'Acer 80 cm (32 inches) I Series HD Ready Android Smart LED TV AR32AR2841HDFL (Black)',
 'Tizum High Speed HDMI Cable with Ethernet | Supports 3D 4K | for All HDMI Devices Laptop Computer Gaming Console TV Set Top Box (1.5 Meter/ 5 Feet)',
 'OnePlus 80 cm (32 inches) Y Series HD Ready LED Smart Android TV 32Y1 (Black)',
 'Ambrane Unbreakable 3 in 1 Fast Charging Braided Multipurpose Cable for Speaker with 2.1 A Speed - 1.25 meter, Black',
 'Duracell USB C To Lightning Apple Certified (Mfi) Braided Sync & Charge Cable For Iphone, Ipad And Ipod. Fast Charging Lightning Cable, 3.9 Feet (1.2M) - Black',
 'boAt A400 USB Type-C to USB-A 2.0 Male Data Cable, 2 Meter (Black)',
 'AmazonBasics USB 2.0 - A-Male to A-Female Extension Cable for Personal Computer, Printer (Black, 9.8 Feet/3 Meters)',
 'Ambrane 60W / 3A Type C Fast Charging Unbreakable 1.5m L Shaped Braided Cable, PD Technology, 480Mbps Data Transfer for Smartphones, Tablet, Laptops & other type c devices (ABLC10, Black)',
 'Zoul USB C 60W Fast Charging 3A 6ft/2M Long Type C Nylon Braided Data Cable Quick Charger Cable QC 3.0 for Samsung Galaxy M31S M30 S10 S9 S20 Plus, Note 10 9 8, A20e A40 A50 A70 (2M, Grey)',
 'Samsung Original Type C to C Cable - 3.28 Feet (1 Meter), White',
 'pTron Solero T351 3.5Amps Fast Charging Type-C to Type-C PD Data & Charging USB Cable, Made in India, 480Mbps Data Sync, Durable 1 Meter Long Cable for Type-C Smartphones, Tablets & Laptops (Black)',
 'pTron Solero MB301 3A Micro USB Data & Charging Cable, Made in India, 480Mbps Data Sync, Strong & Durable 1.5-Meter Nylon Braided USB Cable for Micro USB Devices - (Black)',
 'Amazonbasics Nylon Braided Usb-C To Lightning Cable, Fast Charging Mfi Certified Smartphone, Iphone Charger (6-Foot, Dark Grey)',
 'Sounce 65W OnePlus Dash Warp Charge Cable, 6.5A Type-C to USB C PD Data Sync Fast Charging Cable Compatible with One Plus 8T/ 9/ 9R/ 9 pro/ 9RT/ 10R/ Nord & for All Type C Devices – Red, 1 Meter',
 'OnePlus 126 cm (50 inches) Y Series 4K Ultra HD Smart Android LED TV 50Y1S Pro (Black)',
 'Duracell Type C To Type C 5A (100W) Braided Sync & Fast Charging Cable, 3.9 Feet (1.2M). USB C to C Cable, Supports PD & QC 3.0 Charging, 5 GBPS Data Transmission – Black',
 'AmazonBasics USB 2.0 Cable - A-Male to B-Male - for Personal Computer, Printer- 6 Feet (1.8 Meters), Black',
 'Mi 108 cm (43 inches) Full HD Android LED TV 4C | L43M6-INC (Black)',
 'Wayona Nylon Braided 3A Lightning to USB A Syncing and Fast Charging Data Cable for iPhone, Ipad (3 FT Pack of 1, Black)',
 'TP-Link Nano AC600 USB Wi-Fi Adapter(Archer T2U Nano)- 2.4G/5G Dual Band Wireless Network Adapter for PC Desktop Laptop, Mini Travel Size, Supports Windows 11,10, 8.1, 8, 7, XP/Mac OS 10.9-10.15',
 'FLiX (Beetel USB to Micro USB PVC Data Sync & 2A Fast Charging Cable, Made in India, 480Mbps Data Sync, Solid Cable, 1 Meter Long USB Cable for Micro USB Devices (White)(XCD-M11)',
 'Wecool Nylon Braided Multifunction Fast Charging Cable For Android Smartphone, Ios And Type C Usb Devices, 3 In 1 Charging Cable, 3A, (3 Feet) (Black)',
 'D-Link DWA-131 300 Mbps Wireless Nano USB Adapter (Black)',
 'Amazon Basics High-Speed HDMI Cable, 6 Feet - Supports Ethernet, 3D, 4K video,Black',
 '7SEVEN® Compatible for Samsung Smart 4K Ultra HD TV Monitor Remote Control Replacement of Original Samsung TV Remote for LED OLED UHD QLED and Suitable for 6 7 8 Series Samsung TV with Hot Keys BN59-01259E',
 'Amazonbasics Micro Usb Fast Charging Cable For Android Smartphone,Personal Computer,Printer With Gold Plated Connectors (6 Feet, Black)',
 'TP-Link AC600 600 Mbps WiFi Wireless Network USB Adapter for Desktop PC with 2.4GHz/5GHz High Gain Dual Band 5dBi Antenna Wi-Fi, Supports Windows 11/10/8.1/8/7/XP, Mac OS 10.15 and earlier (Archer T2U Plus)',
 'AmazonBasics Micro USB Fast Charging Cable for Android Phones with Gold Plated Connectors (3 Feet, Black)',
 'AmazonBasics New Release Nylon USB-A to Lightning Cable Cord, Fast Charging MFi Certified Charger for Apple iPhone, iPad (6-Ft, Rose Gold)',
 'VW 80 cm (32 inches) Frameless Series HD Ready LED TV VW32A (Black)',
 'Ambrane Unbreakable 3A Fast Charging Braided Type C Cable    1.5 Meter (RCT15, Blue) Supports QC 2.0/3.0 Charging',
 'Tata Sky Universal Remote',
 'TP-LINK WiFi Dongle 300 Mbps Mini Wireless Network USB Wi-Fi Adapter for PC Desktop Laptop(Supports Windows 11/10/8.1/8/7/XP, Mac OS 10.9-10.15 and Linux, WPS, Soft AP Mode, USB 2.0) (TL-WN823N),Black',
 'OnePlus 80 cm (32 inches) Y Series HD Ready Smart Android LED TV 32 Y1S (Black)',
 'Wecool Unbreakable 3 in 1 Charging Cable with 3A Speed, Fast Charging Multi Purpose Cable 1.25 Mtr Long, Type C cable, Micro Usb Cable and Cable for iPhone, White',
 'Portronics Konnect L 1.2Mtr, Fast Charging 3A Micro USB Cable with Charge & Sync Function (Grey)',
 'Airtel DigitalTV DTH Television, Setup Box Remote Compatible for SD and HD Recording (Black)',
 'Samsung 108 cm (43 inches) Crystal 4K Neo Series Ultra HD Smart LED TV UA43AUE65AKXXL (Black)',
 'Lapster 1.5 mtr USB 2.0 Type A Male to USB A Male Cable for computer and laptop',
 'AmazonBasics USB Type-C to USB Type-C 2.0 Cable - 3 Feet Laptop (0.9 Meters) - White',
 'Redmi 80 cm (32 inches) Android 11 Series HD Ready Smart LED TV | L32M6-RA/L32M7-RA (Black)',
 'Amazon Basics High-Speed HDMI Cable, 6 Feet (2-Pack),Black',
 'Portronics Konnect L 20W PD Quick Charge Type-C to 8-Pin USB Mobile Charging Cable, 1.2M, Tangle Resistant, Fast Data Sync(Grey)',
 'Acer 80 cm (32 inches) N Series HD Ready TV AR32NSV53HD (Black)',
 "Model-P4 6 Way Swivel Tilt Wall Mount 32-55-inch Full Motion Cantilever for LED,LCD and Plasma TV's",
 'Amazon Basics USB Type-C to USB-A 2.0 Male Fast Charging Cable for Laptop - 3 Feet (0.9 Meters), Black',
 'oraimo 65W Type C to C Fast Charging Cable USB C to USB C Cable High Speed Syncing, Nylon Braided 1M length with LED Indicator Compatible For Laptop, Macbook, Samsung Galaxy S22 S20 S10 S20Fe S21 S21 Ultra A70 A51 A71 A50S M31 M51 M31S M53 5G',
 'CEDO 65W OnePlus Dash Warp Charge Cable, USB A to Type C Data Sync Fast Charging Cable Compatible with One Plus 3 /3T /5 /5T /6 /6T /7 /7T /7 pro & for All Type C Devices - 1 Meter, Red',
 'Redmi 108 cm (43 inches) 4K Ultra HD Android Smart LED TV X43 | L43R7-7AIN (Black)',
 'Pinnaclz Original Combo of 2 Micro USB Fast Charging Cable, USB Charging Cable for Data Transfer Perfect for Android Smart Phones White 1.2 Meter Made in India (Pack of 2)',
 'boAt Type C A750 Stress Resistant, Tangle-free, Sturdy Flat Cable with 6.5A Fast Charging & 480Mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Rebellious Black)',
 'Ambrane 2 in 1 Type-C & Micro USB Cable with 60W / 3A Fast Charging, 480 mbps High Data, PD Technology & Quick Charge 3.0, Compatible with All Type-C & Micro USB Devices (ABDC-10, Black)',
 'Ambrane 60W / 3A Fast Charging Output Cable with Type-C to USB for Mobile, Neckband, True Wireless Earphone Charging, 480mbps Data Sync Speed, 1m Length (ACT - AZ10, Black)',
 'TCL 80 cm (32 inches) HD Ready Certified Android Smart LED TV 32S5205 (Black)',
 'SWAPKART Fast Charging Cable and Data Sync USB Cable Compatible for iPhone 6/6S/7/7+/8/8+/10/11, 12, 13 Pro max iPad Air/Mini, iPod and iOS Devices (White)',
 'Firestick Remote',
 'Wayona Usb Nylon Braided Data Sync And Charging Cable For Iphone, Ipad Tablet (Red, Black)',
 'Flix (Beetel) Usb To Type C Pvc Data Sync And 2A 480Mbps Data Sync, Tough Fast Charging Long Cable For Usb Type C Devices, Charging Adapter (White, 1 Meter) - Xcd-C12',
 'SKYWALL 81.28 cm (32 inches) HD Ready Smart LED TV 32SWELS-PRO (Black)',
 'boAt A 350 Type C Cable for Smartphone, Charging Adapter (1.5m, Carbon Black)',
 'Wayona Usb Type C Fast Charger Cable Fast Charging Usb C Cable/Cord Compatible For Samsung Galaxy S10E S10 S9 S8 Plus S10+,Note 10 Note 9 Note 8,S20,M31S,M40,Realme X3,Pixel 2 Xl (3 Ft Pack Of 1,Grey)',
 'OnePlus 108 cm (43 inches) Y Series 4K Ultra HD Smart Android LED TV 43Y1S Pro (Black)',
 'Acer 127 cm (50 inches) I Series 4K Ultra HD Android Smart LED TV AR50AR2851UDFL (Black)',
 'Samsung 108 cm (43 inches) Crystal 4K Series Ultra HD Smart LED TV UA43AUE60AKLXL (Black)',
 'Lapster 65W compatible for OnePlus Dash Warp Charge Cable , type c to c cable fast charging Data Sync Cable Compatible with One Plus 10R / 9RT/ 9 pro/ 9R/ 8T/ 9/ Nord & for All Type C Devices – Red, 1 Meter',
 'Wayona Nylon Braided (2 Pack) Lightning Fast Usb Data Cable Fast Charger Cord For Iphone, Ipad Tablet (3 Ft Pack Of 2, Grey)',
 'Gizga Essentials USB WiFi Adapter for PC, 150 Mbps Wireless Network Adapter for Desktop - Nano Size WiFi Dongle Compatible with Windows, Mac OS & Linux Kernel | WPA/WPA2 Encryption Standards| Black',
 'OnePlus 108 cm (43 inches) Y Series Full HD Smart Android LED TV 43 Y1S (Black)',
 'boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Mercurial Black)',
 'Lapster USB 3.0 A to Micro B SuperSpeed for hard disk cable - short cable',
 'TCL 100 cm (40 inches) Full HD Certified Android R Smart LED TV 40S6505 (Black)',
 'ZEBRONICS ZEB-USB150WF1 WiFi USB Mini Adapter Supports 150 Mbps Wireless Data, Comes with Advanced Security WPA/WPA2 encryption Standards',
 'LOHAYA Remote Compatible for Mi Smart LED TV 4A Remote Control (32"/43") [ Compatible for Mi Tv Remote Control ] [ Compatible for Mi Smart LED Tv Remote Control ]',
 'Gilary Multi Charging Cable, 3 in 1 Nylon Braided Fast Charging Cable for iPhone Micro USB Type C Mobile Phone | Colour May Vary |',
 'TP-Link UE300 USB 3.0 to RJ45 Gigabit Ethernet Network Adapter - Plug and Play',
 'Wayona Type C to Lightning MFI Certified 20W Fast charging Nylon Braided USB C Cable for iPhone 14, 14 Pro, 14 Pro Max, 14 Plus, 13, 13 Pro, 13 Pro Max, 13 Mini, 12, 12 Pro, 11, 11 Pro Max iPhone 12 Mini, X, 8 (2M, Grey)']

In [198]:
#In this dataset, 
#the first word in the product name is most likely the brand name 
#— not for all of them, but for most of them.
# Look at what the raw first word looks like before cleaning
print(df['Product Name'].str.split(' ').str[0].value_counts().head(100))

Product Name
boAt            67
Samsung         36
AmazonBasics    33
Portronics      31
Ambrane         29
Redmi           26
Fire-Boltt      26
Bajaj           26
Amazon          25
Wayona          24
Noise           24
MI              21
HP              21
Duracell        20
Havells         19
Philips         18
TP-Link         17
SanDisk         17
Zebronics       16
Logitech        15
Crompton        15
ZEBRONICS       14
iQOO            14
AGARO           14
Prestige        14
pTron           13
OnePlus         13
KENT            13
Gizga           12
Classmate       12
Lifelong        12
Sounce          11
7SEVEN®         11
STRIFF          11
Boult           11
Pigeon          11
Lapster         10
Acer             9
Lenovo           8
JBL              8
Usha             8
Mi               7
FLiX             7
PTron            7
Belkin           7
Eureka           7
Wipro            7
iBELL            7
LG               6
Airtel           6
Storite          6
Nokia            6
Tukzer           6
Parker           6
USHA             6
INALSA           6
Borosil          6
Sujata           6
Flix             5
Zoul             5
Amazonbasics     5
Wecool           5
LOHAYA           5
Kodak            5
realme           5
WeCool           5
Robustrion       5
Redgear          5
Morphy           5
PrettyKrafts     5
Butterfly        5
PHILIPS          5
Kuber            5
VW               4
Tata             4
Pinnaclz         4
TCL              4
SWAPKART         4
VU               4
Croma            4
Spigen           4
KINGONE          4
Dell             4
Casio            4
DIGITEK®         4
AirCase          4
HUL              4
InstaCuppa       4
Inalsa           4
Tizum            3
D-Link           3
Electvision      3
BlueRigger       3
Sony             3
POPIO            3
Synqe            3
OPPO             3
Tygot            3
URBN             3
LAPSTER          3
Name: count, dtype: int64

In [199]:
# Clean product names 
#(Trim, Clean, and replace multiple spaces with one)
df['Product Name'] = df['Product Name'].str.strip().replace(r'\s+',' ',regex=True)

In [200]:
# Extract first word before the space into a new 'Brand' column
df['Brand'] = df['Product Name'].str.split(' ').str[0]

In [202]:
df.columns

Index(['Product Id', 'Product Name', 'Category', 'Discounted Price',
       'Actual Price', 'Discount Percentage', 'Rating', 'Rating Count',
       'User Id', 'User Name', 'Review Id', 'Sub Category', 'Brand'],
      dtype='str')

In [205]:
# Strip out trademark symbols and commas
df['Brand'] = df['Brand'].str.replace('™','',regex=False)
df['Brand'] = df['Brand'].str.replace('®','',regex=False)
df['Brand'] = df['Brand'].str.replace(',','',regex=False)

In [206]:
# Map specific messy names to their clean versions or "Unknown".
brand_map = {
    'iPhone': 'Apple', '3M': 'Unknown', '4': 'Unknown', '10k': 'Unknown',
    '!!HANEUL!!1000': 'Unknown', '10WeRun': 'WeRun', '!!1000': 'Unknown',
    'SoniVision': 'Soni', 'realme': 'Realme', 'USB': 'Oraimo', 'Amozo': 'Unknown',
    'Noise_Colorfit': 'Unknown', 'Brand': 'Unknown', 'TABLE': 'Unknown',
    'R': 'Unknown', 'Dr': 'Unknown', 'Tom': 'Unknown', 'Multifunctional': 'Unknown',
    'MUnknown.': 'Unknown', 'Unknownacold': 'Unknown', 'T': 'Unknown',
    'Empty': 'Unknown', 'Cafe': 'Unknown', 'SUJAUnknownA': 'Unknown',
    'CAUnknownDEX': 'CARDEX', 'Eco': 'Unknown', 'Monitor': 'Unknown',
    'Aqua': 'Unknown', 'Model-PUnknown': 'Unknown'
}
df['Brand'] = df['Brand'].replace(brand_map)

In [210]:
# Verify the clean product names and new brand column
df[['Product Name','Brand']].head(100)

,Product Name,Brand
0,"Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)",Wayona
1,"Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)",Ambrane
2,"Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices",Sounce
3,"boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)",boAt
4,"Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)",Portronics
5,"pTron Solero TB301 3A Type-C Data and Fast Charging Cable, Made in India, 480Mbps Data Sync, Strong and Durable 1.5-Meter Nylon Braided USB Cable for Type-C Devices for Charging Adapter (Black)",pTron
6,"boAt Micro USB 55 Tangle-free, Sturdy Micro USB Cable with 3A Fast Charging & 480mbps Data Transmission (Black)",boAt
7,MI Usb Type-C Cable Smartphone (Black),MI
8,"TP-Link USB WiFi Adapter for PC(TL-WN725N), N150 Wireless Network Adapter for Desktop - Nano Size WiFi Dongle Compatible with Windows 11/10/7/8/8.1/XP/ Mac OS 10.9-10.15 Linux Kernel 2.6.18-4.4.3",TP-Link
9,"Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Micro USB Cable for Smartphones, Tablets, Laptops & Other Micro USB Devices, 480Mbps Data Sync, Quick Charge 3.0 (RCM15, Black)",Ambrane
10,Portronics Konnect L POR-1081 Fast Charging 3A Type-C Cable 1.2Meter with Charge & Sync Function for All Type-C Devices (Grey),Portronics
11,boAt Rugged v3 Extra Tough Unbreakable Braided Micro USB Cable 1.5 Meter (Black),boAt
12,"AmazonBasics Flexible Premium HDMI Cable (Black, 4K@60Hz, 18Gbps), 3-Foot",AmazonBasics
13,"Portronics Konnect CL 20W POR-1067 Type-C to 8 Pin USB 1.2M Cable with Power Delivery & 3A Quick Charge Support, Nylon Braided for All Type-C and 8 Pin Devices, Green",Portronics
14,Portronics Konnect L 1.2M POR-1401 Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function (White),Portronics
15,MI Braided USB Type-C Cable for Charging Adapter (Red),MI
16,MI 80 cm (32 inches) 5A Series HD Ready Smart Android LED TV L32M7-5AIN (Black),MI
17,"Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C to Type C Cable for Smartphones, Tablets, Laptops & Other Type C Devices, PD Technology, 480Mbps Data Sync (RCTT15, Black)",Ambrane
18,"boAt Type C A325 Tangle-free, Sturdy Type C Cable with 3A Rapid Charging & 480mbps Data Transmission(Black)",boAt
19,LG 80 cm (32 inches) HD Ready Smart LED TV 32LM563BPTC (Dark Iron Gray),LG
20,"Duracell USB Lightning Apple Certified (Mfi) Braided Sync & Charge Cable For Iphone, Ipad And Ipod. Fast Charging Lightning Cable, 3.9 Feet (1.2M) - Black",Duracell
21,"tizum HDMI to VGA Adapter Cable 1080P for Projector, Computer, Laptop, TV, Projectors & TV",tizum
22,Samsung 80 cm (32 Inches) Wondertainment Series HD Ready LED Smart TV UA32T4340BKXXL (Glossy Black),Samsung
23,Flix Micro Usb Cable For Smartphone (Black),Flix
24,Acer 80 cm (32 inches) I Series HD Ready Android Smart LED TV AR32AR2841HDFL (Black),Acer
25,Tizum High Speed HDMI Cable with Ethernet | Supports 3D 4K | for All HDMI Devices Laptop Computer Gaming Console TV Set Top Box (1.5 Meter/ 5 Feet),Tizum
26,OnePlus 80 cm (32 inches) Y Series HD Ready LED Smart Android TV 32Y1 (Black),OnePlus
27,"Ambrane Unbreakable 3 in 1 Fast Charging Braided Multipurpose Cable for Speaker with 2.1 A Speed - 1.25 meter, Black",Ambrane
28,"Duracell USB C To Lightning Apple Certified (Mfi) Braided Sync & Charge Cable For Iphone, Ipad And Ipod. Fast Charging Lightning Cable, 3.9 Feet (1.2M) - Black",Duracell
29,"boAt A400 USB Type-C to USB-A 2.0 Male Data Cable, 2 Meter (Black)",boAt
30,"AmazonBasics USB 2.0 - A-Male to A-Female Extension Cable for Personal Computer, Printer (Black, 9.8 Feet/3 Meters)",AmazonBasics
31,"Ambrane 60W / 3A Type C Fast Charging Unbreakable 1.5m L Shaped Braided Cable, PD Technology, 480Mbps Data Transfer for Smartphones, Tablet, Laptops & other type c devices (ABLC10, Black)",Ambrane
32,"Zoul USB C 60W Fast Charging 3A 6ft/2M Long Type C Nylon Braided Data Cable Quick Charger Cable QC 3.0 for Samsung Galaxy M31S M30 S10 S9 S20 Plus, Note 10 9 8, A20e A40 A50 A70 (2M, Grey)",Zoul
33,"Samsung Original Type C to C Cable - 3.28 Feet (1 Meter), White",Samsung
34,"pTron Solero T351 3.5Amps Fast Charging Type-C to Type-C PD Data & Charging USB Cable, Made in India, 480Mbps Data Sync, Durable 1 Meter Long Cable for Type-C Smartphones, Tablets & Laptops (Black)",pTron
35,"pTron Solero MB301 3A Micro USB Data & Charging Cable, Made in India, 480Mbps Data Sync, Strong & Durable 1.5-Meter Nylon Braided USB Cable for Micro USB Devices - (Black)",pTron
36,"Amazonbasics Nylon Braided Usb-C To Lightning Cable, Fast Charging Mfi Certified Smartphone, Iphone Charger (6-Foot, Dark Grey)",Amazonbasics
37,"Sounce 65W OnePlus Dash Warp Charge Cable, 6.5A Type-C to USB C PD Data Sync Fast Charging Cable Compatible with One Plus 8T/ 9/ 9R/ 9 pro/ 9RT/ 10R/ Nord & for All Type C Devices – Red, 1 Meter",Sounce
38,OnePlus 126 cm (50 inches) Y Series 4K Ultra HD Smart Android LED TV 50Y1S Pro (Black),OnePlus
39,"Duracell Type C To Type C 5A (100W) Braided Sync & Fast Charging Cable, 3.9 Feet (1.2M). USB C to C Cable, Supports PD & QC 3.0 Charging, 5 GBPS Data Transmission – Black",Duracell
40,"AmazonBasics USB 2.0 Cable - A-Male to B-Male - for Personal Computer, Printer- 6 Feet (1.8 Meters), Black",AmazonBasics
41,Mi 108 cm (43 inches) Full HD Android LED TV 4C | L43M6-INC (Black),Mi
42,"Wayona Nylon Braided 3A Lightning to USB A Syncing and Fast Charging Data Cable for iPhone, Ipad (3 FT Pack of 1, Black)",Wayona
43,"TP-Link Nano AC600 USB Wi-Fi Adapter(Archer T2U Nano)- 2.4G/5G Dual Band Wireless Network Adapter for PC Desktop Laptop, Mini Travel Size, Supports Windows 11,10, 8.1, 8, 7, XP/Mac OS 10.9-10.15",TP-Link
44,"FLiX (Beetel USB to Micro USB PVC Data Sync & 2A Fast Charging Cable, Made in India, 480Mbps Data Sync, Solid Cable, 1 Meter Long USB Cable for Micro USB Devices (White)(XCD-M11)",FLiX
45,"Wecool Nylon Braided Multifunction Fast Charging Cable For Android Smartphone, Ios And Type C Usb Devices, 3 In 1 Charging Cable, 3A, (3 Feet) (Black)",Wecool
46,D-Link DWA-131 300 Mbps Wireless Nano USB Adapter (Black),D-Link
47,"Amazon Basics High-Speed HDMI Cable, 6 Feet - Supports Ethernet, 3D, 4K video,Black",Amazon
48,7SEVEN® Compatible for Samsung Smart 4K Ultra HD TV Monitor Remote Control Replacement of Original Samsung TV Remote for LED OLED UHD QLED and Suitable for 6 7 8 Series Samsung TV with Hot Keys BN59-01259E,7SEVEN
49,"Amazonbasics Micro Usb Fast Charging Cable For Android Smartphone,Personal Computer,Printer With Gold Plated Connectors (6 Feet, Black)",Amazonbasics
50,"TP-Link AC600 600 Mbps WiFi Wireless Network USB Adapter for Desktop PC with 2.4GHz/5GHz High Gain Dual Band 5dBi Antenna Wi-Fi, Supports Windows 11/10/8.1/8/7/XP, Mac OS 10.15 and earlier (Archer T2U Plus)",TP-Link
51,"AmazonBasics Micro USB Fast Charging Cable for Android Phones with Gold Plated Connectors (3 Feet, Black)",AmazonBasics
52,"AmazonBasics New Release Nylon USB-A to Lightning Cable Cord, Fast Charging MFi Certified Charger for Apple iPhone, iPad (6-Ft, Rose Gold)",AmazonBasics
53,VW 80 cm (32 inches) Frameless Series HD Ready LED TV VW32A (Black),VW
54,"Ambrane Unbreakable 3A Fast Charging Braided Type C Cable 1.5 Meter (RCT15, Blue) Supports QC 2.0/3.0 Charging",Ambrane
55,Tata Sky Universal Remote,Tata
56,"TP-LINK WiFi Dongle 300 Mbps Mini Wireless Network USB Wi-Fi Adapter for PC Desktop Laptop(Supports Windows 11/10/8.1/8/7/XP, Mac OS 10.9-10.15 and Linux, WPS, Soft AP Mode, USB 2.0) (TL-WN823N),Black",TP-LINK
57,OnePlus 80 cm (32 inches) Y Series HD Ready Smart Android LED TV 32 Y1S (Black),OnePlus
58,"Wecool Unbreakable 3 in 1 Charging Cable with 3A Speed, Fast Charging Multi Purpose Cable 1.25 Mtr Long, Type C cable, Micro Usb Cable and Cable for iPhone, White",Wecool
59,"Portronics Konnect L 1.2Mtr, Fast Charging 3A Micro USB Cable with Charge & Sync Function (Grey)",Portronics
60,"Airtel DigitalTV DTH Television, Setup Box Remote Compatible for SD and HD Recording (Black)",Airtel
61,Samsung 108 cm (43 inches) Crystal 4K Neo Series Ultra HD Smart LED TV UA43AUE65AKXXL (Black),Samsung
62,Lapster 1.5 mtr USB 2.0 Type A Male to USB A Male Cable for computer and laptop,Lapster
63,AmazonBasics USB Type-C to USB Type-C 2.0 Cable - 3 Feet Laptop (0.9 Meters) - White,AmazonBasics
64,Redmi 80 cm (32 inches) Android 11 Series HD Ready Smart LED TV | L32M6-RA/L32M7-RA (Black),Redmi
65,"Amazon Basics High-Speed HDMI Cable, 6 Feet (2-Pack),Black",Amazon
66,"Portronics Konnect L 20W PD Quick Charge Type-C to 8-Pin USB Mobile Charging Cable, 1.2M, Tangle Resistant, Fast Data Sync(Grey)",Portronics
67,Acer 80 cm (32 inches) N Series HD Ready TV AR32NSV53HD (Black),Acer
68,"Model-P4 6 Way Swivel Tilt Wall Mount 32-55-inch Full Motion Cantilever for LED,LCD and Plasma TV's",Model-P4
69,"Amazon Basics USB Type-C to USB-A 2.0 Male Fast Charging Cable for Laptop - 3 Feet (0.9 Meters), Black",Amazon
70,"oraimo 65W Type C to C Fast Charging Cable USB C to USB C Cable High Speed Syncing, Nylon Braided 1M length with LED Indicator Compatible For Laptop, Macbook, Samsung Galaxy S22 S20 S10 S20Fe S21 S21 Ultra A70 A51 A71 A50S M31 M51 M31S M53 5G",oraimo
71,"CEDO 65W OnePlus Dash Warp Charge Cable, USB A to Type C Data Sync Fast Charging Cable Compatible with One Plus 3 /3T /5 /5T /6 /6T /7 /7T /7 pro & for All Type C Devices - 1 Meter, Red",CEDO
72,Redmi 108 cm (43 inches) 4K Ultra HD Android Smart LED TV X43 | L43R7-7AIN (Black),Redmi
73,"Pinnaclz Original Combo of 2 Micro USB Fast Charging Cable, USB Charging Cable for Data Transfer Perfect for Android Smart Phones White 1.2 Meter Made in India (Pack of 2)",Pinnaclz
74,"boAt Type C A750 Stress Resistant, Tangle-free, Sturdy Flat Cable with 6.5A Fast Charging & 480Mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Rebellious Black)",boAt
75,"Ambrane 2 in 1 Type-C & Micro USB Cable with 60W / 3A Fast Charging, 480 mbps High Data, PD Technology & Quick Charge 3.0, Compatible with All Type-C & Micro USB Devices (ABDC-10, Black)",Ambrane
76,"Ambrane 60W / 3A Fast Charging Output Cable with Type-C to USB for Mobile, Neckband, True Wireless Earphone Charging, 480mbps Data Sync Speed, 1m Length (ACT - AZ10, Black)",Ambrane
77,TCL 80 cm (32 inches) HD Ready Certified Android Smart LED TV 32S5205 (Black),TCL
78,"SWAPKART Fast Charging Cable and Data Sync USB Cable Compatible for iPhone 6/6S/7/7+/8/8+/10/11, 12, 13 Pro max iPad Air/Mini, iPod and iOS Devices (White)",SWAPKART
79,Firestick Remote,Firestick
80,"Wayona Usb Nylon Braided Data Sync And Charging Cable For Iphone, Ipad Tablet (Red, Black)",Wayona
81,"Flix (Beetel) Usb To Type C Pvc Data Sync And 2A 480Mbps Data Sync, Tough Fast Charging Long Cable For Usb Type C Devices, Charging Adapter (White, 1 Meter) - Xcd-C12",Flix
82,SKYWALL 81.28 cm (32 inches) HD Ready Smart LED TV 32SWELS-PRO (Black),SKYWALL
83,"boAt A 350 Type C Cable for Smartphone, Charging Adapter (1.5m, Carbon Black)",boAt
84,"Wayona Usb Type C Fast Charger Cable Fast Charging Usb C Cable/Cord Compatible For Samsung Galaxy S10E S10 S9 S8 Plus S10+,Note 10 Note 9 Note 8,S20,M31S,M40,Realme X3,Pixel 2 Xl (3 Ft Pack Of 1,Grey)",Wayona
85,OnePlus 108 cm (43 inches) Y Series 4K Ultra HD Smart Android LED TV 43Y1S Pro (Black),OnePlus
86,Acer 127 cm (50 inches) I Series 4K Ultra HD Android Smart LED TV AR50AR2851UDFL (Black),Acer
87,Samsung 108 cm (43 inches) Crystal 4K Series Ultra HD Smart LED TV UA43AUE60AKLXL (Black),Samsung
88,"Lapster 65W compatible for OnePlus Dash Warp Charge Cable , type c to c cable fast charging Data Sync Cable Compatible with One Plus 10R / 9RT/ 9 pro/ 9R/ 8T/ 9/ Nord & for All Type C Devices – Red, 1 Meter",Lapster
89,"Wayona Nylon Braided (2 Pack) Lightning Fast Usb Data Cable Fast Charger Cord For Iphone, Ipad Tablet (3 Ft Pack Of 2, Grey)",Wayona
90,"Gizga Essentials USB WiFi Adapter for PC, 150 Mbps Wireless Network Adapter for Desktop - Nano Size WiFi Dongle Compatible with Windows, Mac OS & Linux Kernel | WPA/WPA2 Encryption Standards| Black",Gizga
91,OnePlus 108 cm (43 inches) Y Series Full HD Smart Android LED TV 43 Y1S (Black),OnePlus
92,"boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Mercurial Black)",boAt
93,Lapster USB 3.0 A to Micro B SuperSpeed for hard disk cable - short cable,Lapster
94,TCL 100 cm (40 inches) Full HD Certified Android R Smart LED TV 40S6505 (Black),TCL
95,"ZEBRONICS ZEB-USB150WF1 WiFi USB Mini Adapter Supports 150 Mbps Wireless Data, Comes with Advanced Security WPA/WPA2 encryption Standards",ZEBRONICS
96,"LOHAYA Remote Compatible for Mi Smart LED TV 4A Remote Control (32""/43"") [ Compatible for Mi Tv Remote Control ] [ Compatible for Mi Smart LED Tv Remote Control ]",LOHAYA
97,"Gilary Multi Charging Cable, 3 in 1 Nylon Braided Fast Charging Cable for iPhone Micro USB Type C Mobile Phone | Colour May Vary |",Gilary
98,TP-Link UE300 USB 3.0 to RJ45 Gigabit Ethernet Network Adapter - Plug and Play,TP-Link
99,"Wayona Type C to Lightning MFI Certified 20W Fast charging Nylon Braided USB C Cable for iPhone 14, 14 Pro, 14 Pro Max, 14 Plus, 13, 13 Pro, 13 Pro Max, 13 Mini, 12, 12 Pro, 11, 11 Pro Max iPhone 12 Mini, X, 8 (2M, Grey)",Wayona

In [211]:
df.to_csv('amazon-python.csv',index=False,encoding='utf-8-sig')

In [213]:
#Taking another look at the dataset, trying to find anything that needs to be cleaned.
df.head(100)

,Product Id,Product Name,Category,Discounted Price,Actual Price,Discount Percentage,Rating,Rating Count,User Id,User Name,Review Id,Sub Category,Brand
0,B07JW9H4J1,"Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)",Computers&Accessories,399.00,1099.00,64%,4.2,"24,269","AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBBSNLYT3ONILA,AHCTC6ULH4XB6YHDY6PCH2R772LQ,AGYHHIERNXKA6P5T7CZLXKVPT7IQ,AG4OGOFWXJZTQ2HKYIOCOY3KXF2Q,AENGU523SXMOS7JPDTW52PNNVWGQ,AEQJHCVTNINBS4FKTBGQRQTGTE5Q,AFC3FFC5PKFF5PMA52S3VCHOZ5FQ","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jaspreet singh,Khaja moin,Anand,S.ARUMUGAM","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1KD19VHEDV0OR,R3C02RMYQMK6FC,R39GQRVBUZBWGY,R2K9EDOE15QIRJ,R3OI7YT648TL8I",Accessories&Peripherals,Wayona
1,B098NS6PVG,"Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)",Computers&Accessories,199.00,349.00,43%,4.0,"43,994","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBXNGXZJT525AQ,AHONIZU3ICIEHQIGQ6R2VFRSBXOQ,AFPHD2CRPDZMWMBL7WXRSVYWS5JA,AEZ346GX3HJ4O4XNRPHCNHXQURMQ,AEPSWFPNECKO34PUC7I56ITGXR6Q,AHWVEHR5DYLVFTO2KF3IZATFQSWQ,AH4QT33M55677I7ISQOAKEQWACYQ","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,N/A,BharanI,sonia,Niam","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RYGGS0M09S3KY,R17KQRUTAN5DKS,R3AAQGS6HP2QUK,R1HDNOG6TO2CCA,R3PHKXYA5AFEOU",Accessories&Peripherals,Ambrane
2,B096MSW6CT,"Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices",Computers&Accessories,199.00,1899.00,90%,3.9,"7,928","AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQLWQOWZ4N3OA,AHTPQRIMGUD4BYR5YIHBH3CCGEFQ,AEUVWXYP5LT7PZLLZENEO2NODPBQ,AHC7MPW55DOO6WNCOQVA2VHOD26A,AFDI6FRPFBTNBG7BAEB7JDJSMKDQ,AFQKCEEEKXCOHTDG4WUN3XPPHJQQ,AHKUUFNMBZIDLSSPA4FEHIO2EC7Q","Kunal,Himanshu,viswanath,sai niharka,saqib malik,Aashiq,Ramu Challa,Sanjay gupta","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R25X4TBMPY91LX,R27OK7G99VK0TR,R207CYDCHJJTCJ,R3PCU8XMU173BT,R1IMONDOWRNU5V",Accessories&Peripherals,Sounce
3,B08HDJ86NZ,"boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)",Computers&Accessories,329.00,699.00,53%,4.2,"94,363","AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5SGCUQBP7YSCA,AH725ST5NW2Y4JZPKUNTIJCUK2BA,AHV3TXIFCJPMS4D5JATCEUR266MQ,AGWIGDEMFIIUAOXYY2QATNBSUGHA,AFSTSLQUV4EVEXWKBOLEFHL2H5YQ,AGAKDNBHY2FKX7I4ACRGILU7QL7A,AFNWJUWJRHCC6HN52KMG5AKZY37Q","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh chouhan,Ravi Siddan,Himanshu Goel,Udaykumar","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1CLH2ULIVG5U3,R2DMKIBGFKBD6R,RC89B5IAJUTR5,R3B3DDON5FH8DS,R13WAEJDI5RS36",Accessories&Peripherals,boAt
4,B08CF3B7N1,"Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)",Computers&Accessories,154.00,399.00,61%,4.2,"16,905","AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZHM4QB2KPKFUQ,AFK4NJOLFSJGWLOJIUIAROJF6YVA,AFUOTYRFUXVPEBGIXVZZ7DR3CZUA,AFDLRSXKDZ6U3U3KD46SQLFGZQRA,AH5VLM66SIK7J3IRG4NY7XVOQ55A,AE3MQNNHHLUHXURL5S7IAR7JTGNQ,AFSEOFZY67MYC7UAJU264Z5NFTLA","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK,Bhargav,Durai Vignesh,N/A","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R3KK4GT934ST3I,RCFHMWUSBIJO,RDO7DACXMAJ84,R3A6MEZL3LY66Z,R1ESIEKPGAYA29",Accessories&Peripherals,Portronics
5,B08Y1TFSP6,"pTron Solero TB301 3A Type-C Data and Fast Charging Cable, Made in India, 480Mbps Data Sync, Strong and Durable 1.5-Meter Nylon Braided USB Cable for Type-C Devices for Charging Adapter (Black)",Computers&Accessories,149.00,1000.00,85%,3.9,"24,871","AEQ2YMXSZWEOHK2EHTNLOS56YTZQ,AGRVINWECNY7323CWFXZYYIZOFTQ,AHBAT6VLOXWGYDL57KHCNCLPXAKA,AF7NDY2H6JVYTSQOZP76GCATQ34Q,AFV7ZA733ZLME4KNLZPMPCBUNPPA,AHFAAPSY2MJ5HYOU2VQDJ7AQY4NQ,AH2WGV2PEBUTICRPBEEVKF24G5LA,AEP4MK3EKOBDKTGPJTRN5RBDIODA","Jayesh,Rajesh k.,Soopy,N/A,Aman,Shankar,dinesh,Chitra,Ajaybabu.O.M","R7S8ANNSDPR40,R3CLZFLHVJU26P,RFF7U7MPQFUGR,R1MV1NKC23DWPI,R11D3U0V2XKDKF,R18MP1KLUE18PC,RWGJNVEH5ZQME,R1XN72FU6Q37IH",Accessories&Peripherals,pTron
6,B08WRWPM22,"boAt Micro USB 55 Tangle-free, Sturdy Micro USB Cable with 3A Fast Charging & 480mbps Data Transmission (Black)",Computers&Accessories,176.63,499.00,65%,4.1,"15,188","AG7C6DAADCTRQJG2BRS3RIKDT52Q,AFU7BOMPVJ7Q3TTA4G67RASTGYIQ,AER5ZGIXXVYG3AWZTRZT7M2BYCEA,AHE76XQSOLGOP5ZEKTIW6KUPDWBQ,AGXTMB2XHZBEWZ2UIX7ODZ4XTU6Q,AHNM2XVU745EDPNGUOAG74PTSNRA,AH5RWQ4S72IVLZD6O75OPCFIVDXQ,AG322TYKVPLPBDXE7ABEUK5QTALQ","Vivek kumar,N/A,SARTHAK,Chiranjeevi,V V GIRI KUMAR,Rajnandini,Akshay Talla,sudhanshu chaubey","R8E73K2KWJRDS,RSD0JTIIWQQL8,R64CRSTE9SLW1,R2FRTNIIUFJE1F,RWGNX3W7UOJ7W,R32TYHHODHTF5D,RQL9ZMQUTY7P2,R280XJ5VZUBOXV",Accessories&Peripherals,boAt
7,B08DDRGWTJ,MI Usb Type-C Cable Smartphone (Black),Computers&Accessories,229.00,299.00,23%,4.3,"30,411","AHW6E5LQ2BDYOIVLAJGDH45J5V5Q,AF74RSGCHPZITVFSZN76K6GKPICA,AHDD7ZNB47QA2JLYU53HD4ML3VNQ,AHV3ELGDSOWBYUQLXSPDCSHBQRHQ,AEJU4L3ZM2GTILSJZZSNSF6VUOIA,AFVD66VQMSHPDT3A6HBBBGKRXBZA,AELKHQXVSSG6NHXLFJLLNEFRQQUQ,AGYSMAC6V6RFJJOHG2FIRPOZ6CSQ","Pavan A H,Jayesh bagad,Shridhar,rajendran,karuppu k,Akshay wani,Abbimaniu Singh,VISHAL H BADSHE","R2X090D1YHACKR,R32ZCIH9AFNJ60,R3N57EVVG0EHAF,R3QWLE8JHROKC1,R2VTSDOOUTSQ5X,R3E6FZ75Q074KH,R1SYBQLTPFCW20,RYQT96J8HPIXE",Accessories&Peripherals,MI
8,B008IFXQFU,"TP-Link USB WiFi Adapter for PC(TL-WN725N), N150 Wireless Network Adapter for Desktop - Nano Size WiFi Dongle Compatible with Windows 11/10/7/8/8.1/XP/ Mac OS 10.9-10.15 Linux Kernel 2.6.18-4.4.3",Computers&Accessories,499.00,999.00,50%,4.2,"1,79,691","AGV3IEFANZCKECFGUM42MRH5FNOA,AEBO7NWCNXKT4AESAN443HQH35FQ,AE7GD3VRRYQEAHDR7FXJIR23INYA,AHPAW24BI5X2GCX5M2LHI72VSJJQ,AE2VXY4CFO36MDSIMPG43XHNF4GA,AHHQEKUNVETALN7DTRHUQ2WAWEKQ,AFMIFTNTUD5PIHGONWOTRMMZ5EBA,AHOJBIZVVIIFJKRREY4B6ESVA4KA","Azhar JuMan,Anirudh Sood,Hari Krishnan PS,Akash Jindal,PRADEEP,Rajesh,Divya Kothari,abhijit","R1LW6NWSVTVZ2H,R3VR5WFKUS15C5,R2F6GC79OYWUKQ,R3QZ19MECGWG9A,R2MPU42MYK7GPO,R33DVXFB4VYPZZ,R1SQ7OGFR4JRUR,R1S5F9QI0M1VBZ",NetworkingDevices,TP-Link
9,B082LZGK39,"Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Micro USB Cable for Smartphones, Tablets, Laptops & Other Micro USB Devices, 480Mbps Data Sync, Quick Charge 3.0 (RCM15, Black)",Computers&Accessories,199.00,299.00,33%,4.0,"43,994","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBXNGXZJT525AQ,AHONIZU3ICIEHQIGQ6R2VFRSBXOQ,AFPHD2CRPDZMWMBL7WXRSVYWS5JA,AEZ346GX3HJ4O4XNRPHCNHXQURMQ,AEPSWFPNECKO34PUC7I56ITGXR6Q,AHWVEHR5DYLVFTO2KF3IZATFQSWQ,AH4QT33M55677I7ISQOAKEQWACYQ","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,N/A,BharanI,sonia,Niam","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RYGGS0M09S3KY,R17KQRUTAN5DKS,R3AAQGS6HP2QUK,R1HDNOG6TO2CCA,R3PHKXYA5AFEOU",Accessories&Peripherals,Ambrane
10,B08CF3D7QR,Portronics Konnect L POR-1081 Fast Charging 3A Type-C Cable 1.2Meter with Charge & Sync Function for All Type-C Devices (Grey),Computers&Accessories,154.00,339.00,55%,4.3,"13,391","AGYLPKPZHVYKKZHOTHCTYVEDAJ4A,AGTTU64JMX722LYCN3SOWLFPKPAQ,AFWD4ZTM7473CDWARHCDQKK73MTA,AEXCQM3FDLX3YL3UJWWUIAIUJT4A,AHUKYUWRUVRTB3IQGISXWTSPAWLQ,AFWW4UEXAJH7EAB5LTMKMSGLUN2Q,AFM5JL37WY7G6MLQUI4WAXUJME7Q,AFECO24WYFOU2KL7C3DMHTEHRU7Q","Tanya,Anu,Akshay,Vishal Sagara Shetty,Swatilekha Sarkar,Jithindas,IBRAHIM S,Sundaram J.","R11MQS7WD9C3I0,R2AKH69XQY8BY4,R8GBOLYUN5UP6,R1AYVO4R25KJTA,R1HT6XM787V7FV,R339XJL1GMKHA3,R175VFSB2A32HG,R35T9LXYBSP09G",Accessories&Peripherals,Portronics
11,B0789LZTCJ,boAt Rugged v3 Extra Tough Unbreakable Braided Micro USB Cable 1.5 Meter (Black),Computers&Accessories,299.00,799.00,63%,4.2,"94,363","AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5SGCUQBP7YSCA,AH725ST5NW2Y4JZPKUNTIJCUK2BA,AHV3TXIFCJPMS4D5JATCEUR266MQ,AGWIGDEMFIIUAOXYY2QATNBSUGHA,AFSTSLQUV4EVEXWKBOLEFHL2H5YQ,AGAKDNBHY2FKX7I4ACRGILU7QL7A,AFNWJUWJRHCC6HN52KMG5AKZY37Q","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh chouhan,Ravi Siddan,Himanshu Goel,Udaykumar","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1CLH2ULIVG5U3,R2DMKIBGFKBD6R,RC89B5IAJUTR5,R3B3DDON5FH8DS,R13WAEJDI5RS36",Accessories&Peripherals,boAt
12,B07KSMBL2H,"AmazonBasics Flexible Premium HDMI Cable (Black, 4K@60Hz, 18Gbps), 3-Foot",Electronics,219.00,700.00,69%,4.4,"4,26,973","AEYJ5I6JZZPOJB6MGWRQOHRQLPSQ,AFY5TVFOMVHGBPBTIJODYDQRZM5Q,AE3O6366WGEQAANKJ76QETTUQQTQ,AEQIJCPWSBCDKUO5VROXXHWX3PPA,AGVIAQK2HQ47P7UVXHW2NBAEU7YQ,AE3D5CJ2GDUP5SQ3AAYMVAGDTX7A,AH77IQRYD54XCRMCO7XEAIAYCLPA,AEA2HQHMFG3ZGJFOLLJQ65WKIZUQ","Rishav Gossain,Shashank Mallamraju,Purnendu,gunasekaran desomayananam,Anto RK,Sukrit Basak,Manoj Kumar,Sethuram.S","R1FKOKZ3HHKJBZ,R2WNMZI1EXTA0H,RCA1M3W4RIXUR,R3BKCLL6D7ZLIX,REVSR0ILY3547,R15W5KMQB95IV5,R10PB68FRUHT5V,R3TLCE9JSBU3UP","HomeTheater,TV&Video",AmazonBasics
13,B085DTN6R2,"Portronics Konnect CL 20W POR-1067 Type-C to 8 Pin USB 1.2M Cable with Power Delivery & 3A Quick Charge Support, Nylon Braided for All Type-C and 8 Pin Devices, Green",Computers&Accessories,350.00,899.00,61%,4.2,"2,262","AGUAYQHARAKR2VZTRP276KAGETKQ,AFKTST2773VUOKUHE7FCR6QCAURQ,AEGLHOQOWUUUQEDV6EWXTSHIUE7A,AEHQYGI5L4FFALBMC5XMT5KXSZCA,AHJFXFGDAXEHIG2ZLUWVMZ3LWPBA,AEP4CW3UI7AJ7XM7PAAKVCB6U3ZA,AHIWCPCQ2Z4HWEM7V4HGTLVZQM6Q,AHT4JDEYWRIQGCA2WAQJ6E2POHCQ","Priya,Mansi,Plaban,Vivek,Taufique Ahmed,Praveen kumar,Robbin,arjun sharma","R1QETDIPRCX4S0,RARQYQ8POOFA9,R952F931MCOR5,R3LLDHV3WXED9C,R282YHZ5A4GMY4,R34W3B1C7RP98Q,R1467F9VL3DLSY,R3KLQRR1UM44JG",Accessories&Peripherals,Portronics
14,B09KLVMZ3B,Portronics Konnect L 1.2M POR-1401 Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function (White),Computers&Accessories,159.00,399.00,60%,4.1,"4,768","AF2XXVO7JUBUVAOBTJ3MNH4DGUFQ,AH6VDJLLPBXKCWXMLBKMBCQ2ESGA,AE642RIGZIT2VPQJOLNUZ34QVWJQ,AFLHNKQH5UQZU3ATISKSMRE2KEDQ,AF2L4MCRCIDOOREQJN7QPQ4QBZCA,AGKLZ4SUHAU47KJXDVHBBEWJODUA,AHESCOYXLCXB56F4JO45X4CZQCYA,AGGHDE6KFZHEDUDJBD5R27AYMEWA","Deepaak Singh,siva k.,MUNDATH BALGOPAL,BOOPATHI,Rakesh,Ana,Xolo,Rushi","R20XIOU25HEX80,R2X55FA2EEUEYM,R393Z224NBTDLN,R3Q4ZCHWSAQD5B,R1AE3A4NSVM9SC,R2U1YAAZE07I1V,R36NVL58WQ7D64,R1E7GPZ569TBIZ",Accessories&Peripherals,Portronics
15,B083342NKJ,MI Braided USB Type-C Cable for Charging Adapter (Red),Computers&Accessories,349.00,399.00,13%,4.4,"18,757","AGSGSRTEZBQY64WO2HKQTV7TWFSA,AEYD5HVYAJ23CR6PTWOOIKUOIDHA,AFRMNW6TDHDZBP2UHF2K3MEAEYUA,AHICHCW6EC3BNV2IDAEAJPBG4HZQ,AGWFKE7RNP6EVC4JFLFSL76EEVVQ,AGEOQQHGNELZNEUKJAJUA7NTPBLA,AFS3QBSOMCE2FAZFUYZ3NBFQDLMQ,AGJYG6ZWCWD74WNE6Y37XZ2VUSMA","Birendra ku Dash,Aditya Gupta,Abdulla A N,Deepak,Gowtham,Rakesh,Pawan Kumar,Prabhat Raj Pathak","R2JPQNKCOE10UK,RQI80JG2WZXNF,R2LYZ4CUWPMUJN,R1ZBD2ZB2ZYEWX,R2ITEDC9KOCY3N,R1115HIQP3BKKJ,R31OMS6DNMI7M,R2DCFXQMUNO93L",Accessories&Peripherals,MI
16,B0B6F7LX4C,MI 80 cm (32 inches) 5A Series HD Ready Smart Android LED TV L32M7-5AIN (Black),Electronics,13999.00,24999.00,44%,4.2,"32,840","AHEVOQADJSSRX7DS325HSFLMP7VQ,AG7XYZRCSKX6G2OLO7DVZWIZ3PUQ,AE2THTCCQLBIUSWPF4CPXC6GGP7Q,AHUJZOV34DFEN55QQ5XOYKVKHV6Q,AELX4DI77ZHURZTDLYFU7XMP7R6Q,AE2ODWBBOBD2SITDDIEJ644OSRFQ,AFLW4WXYQ3G6HU5LBQORDDZO3FOQ,AGGRC2P6M43GDEWCAHGYAILCSKTQ","Manoj maddheshiya,Manoj Kumar Sahoo,Saumil s.,Jean-Louis M.,Mahesh,syed azhar abbas,prabakaran,Sidhu","R13UTIA6KOF6QV,R2UGDZSGFF01K7,RHHIZ45VYU5X6,R14N9HBE5EIUY0,R2WMW096T9Y0OU,R1SHIIE6M72825,R22P6BE9DBME4F,R2TEINENXTIHT2","HomeTheater,TV&Video",MI
17,B082LSVT4B,"Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C to Type C Cable for Smartphones, Tablets, Laptops & Other Type C Devices, PD Technology, 480Mbps Data Sync (RCTT15, Black)",Computers&Accessories,249.00,399.00,38%,4.0,"43,994","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBXNGXZJT525AQ,AHONIZU3ICIEHQIGQ6R2VFRSBXOQ,AFPHD2CRPDZMWMBL7WXRSVYWS5JA,AEZ346GX3HJ4O4XNRPHCNHXQURMQ,AEPSWFPNECKO34PUC7I56ITGXR6Q,AHWVEHR5DYLVFTO2KF3IZATFQSWQ,AH4QT33M55677I7ISQOAKEQWACYQ","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,N/A,BharanI,sonia,Niam","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RYGGS0M09S3KY,R17KQRUTAN5DKS,R3AAQGS6HP2QUK,R1HDNOG6TO2CCA,R3PHKXYA5AFEOU",Accessories&Peripherals,Ambrane
18,B08WRBG3XW,"boAt Type C A325 Tangle-free, Sturdy Type C Cable with 3A Rapid Charging & 480mbps Data Transmission(Black)",Computers&Accessories,199.00,499.00,60%,4.1,"13,045","AFB5KJR4Q5FICAHBOPDPUTB3O7QQ,AHW3QBHDOUMXODZ4EAMHD5JMDIDQ,AGXRGH7DLS3RVFS5KWU4PGR3H3GQ,AFLIHOX2HH7S2OJAD63UAHKMY34Q,AEHBE4U3HD6G2TMSHKE7TNZYOWCA,AFHKIURZM4R62UEXTOCZLI2FPQ6A,AEW6K4E5A4RUWRFFUDINQE5WWBSQ,AG4LMDCRAAKD4U2FZ6B6N75KTHXA","Rohan Narkar,JAGWINDER SINGH,Gursewak Singh,Avii,Amit Sharma,Ritesh Agarwala,Rahul hardaha,N/A","R2BP8Y5OJXKJLF,R218813TNRHNSY,R3VIKEVJ5DBF5G,R2PQNCTR8TQCT4,R3FI11UEJC9ZOJ,R3ULCCZZHBNLA4,RELIQ4H7CYX2Q,R3ALQNTJN4ER9N",Accessories&Peripherals,boAt
19,B08DPLCM6T,LG 80 cm (32 inches) HD Ready Smart LED TV 32LM563BPTC (Dark Iron Gray),Electronics,13490.00,21990.00,39%,4.3,"11,976","AHBNKB74LGTYUOKPAJBSKNFV45CA,AFIECTV45ADX5YPTE2VU6ORRHTGQ,AFDUJI7KG7VMZF4JGJHV4DBCA4OA,AEUWKSX5ZL7DWOOYVDOWJKBHOVXA,AHEJW5MYVFOQBEXD6BIUBB3PJBPQ,AEM2Y22BKLFYL5BK7SC56Q75ODOQ,AHWDVB4OO4S3YS5RYQZIDBNV6BUQ,AFCEDQXVCB4LUUBWXRJS6KRU62FQ","NIRMAL.N,Manoj kumar,SOMNATH DAS,Harsha,Pradhut Roy,MAHENDRA NATH DAS,Naveen Kumar,Gopi Sahu","R2PNR69G0BQG2F,R31A0WWDEYMKEW,R2C4XEWFLVU7JV,RYWES5AT5FQO6,R1PGWAY5TEWLT4,R32542OPR0QC4I,R2JDJEVZ2G7EEK,R36EHHPAQNSSOF","HomeTheater,TV&Video",LG
20,B09C6HXFC1,"Duracell USB Lightning Apple Certified (Mfi) Braided Sync & Charge Cable For Iphone, Ipad And Ipod. Fast Charging Lightning Cable, 3.9 Feet (1.2M) - Black",Computers&Accessories,970.00,1799.00,46%,4.5,815,"AFNYIBWKJLJQKY4BGK77ZOTVMORA,AFCTNNMP2LZLY5466YJ5AY3JE5ZA,AG3XBWOAL65DJSBHJ7LQ2K54HJKQ,AF2ZFMLJS4UBCGZO4FMJTEPP6MHA,AFBZMRHC4GXUU7KNAK4OBKORDF6Q,AHSIQL276K7X2UP72QOOOWNVRSXA,AF3D6X5NQWOBOEVVH2Y37N55AKZQ,AFWOTSQXCQJLZ653Y7ACEZADKGYQ","Prasannavijayaraghavan G.,Preet Sikka,Theeban Raj,Nishikant,Gurpreet S.,Manoj,SP,Ashutosh","R12D1BZF9MU8TN,R32MNCWO5LGFCG,RZU3UK8OZKD6X,R3BSTKR3JUW6GY,R1ARVYPXS4XPB7,R1V6GDYE2IBX8O,R28EG2PXZTJL90,R2SQNU7OIOOLHT",Accessories&Peripherals,Duracell
21,B085194JFL,"tizum HDMI to VGA Adapter Cable 1080P for Projector, Computer, Laptop, TV, Projectors & TV",Electronics,279.00,499.00,44%,3.7,"10,962","AEO5FHWNOSFBT554DKQAG4ICBGFQ,AGIQ5Y7Q4MKZ542KKVFZLAIZV6GQ,AFD53TWXXCPJAYQJ7REZPW34AKKQ,AHBMHE56M3IAD7Z4KXUKREAZX3WQ,AFR4YULNFZZC5DJOWH2KNFAOM6BQ,AEP5UMK4KDMGZGBHBLZDB2R37OMA,AHLKQWAPXICPCSCIPIF6C6FOENOQ,AHTBS46SCEBGWK4SUH3FOQEORR3Q","aditya d.,Paranthaman,ashik rahman c,Rajas c.,Madan Tejaswi,Sumit,chaitanya srikrishna,subeh sharma","R1GYK05NN6747O,R1J21BZ29NGQF9,R16JCHEILBYOMW,R2WVVS88M7SH18,R2MQ3VB8ZTUS48,RBJPTKHYQ7G7U,R37PKO5FUPJW35,R38R2YC2J2BMWR","HomeTheater,TV&Video",tizum
22,B09F6S8BT6,Samsung 80 cm (32 Inches) Wondertainment Series HD Ready LED Smart TV UA32T4340BKXXL (Glossy Black),Electronics,13490.00,22900.00,41%,4.3,"16,299","AHEVO4Q5NM4YXMG2HDDXC5XMBGRQ,AFZPH7ZAWX5VDY3HOBNYRDGIDBVA,AFURD6VVHRG4HZ36KXGXYUTVUDLA,AHJF5BZJNDLXJXSW74ZPLHGO7GUA,AFUS52CHEA75E2YGQ6SYGP3PKBGA,AGS3YC22FW2PCSH3I7ODDXETZ6BA,AGGI2H2AGOIX6IBDJRWULYUP5DPQ,AG4TU4LCQXF2XTLMMGMFTNWL3OOA","Rahman Ali,MARIYA DASS,Md Aftab,roshan s.,Mohan,Devendu Sawant,Shek hussain,Prathap Pathaneni","R1SN0D4DFBKAZI,R1SX5L77L2CD6V,R1NAZ6M4QBUJMK,R25I5FXOJA76KS,R32V7DQLDSKJ99,R8QWY8HXI120P,R2OZPGGMUCLSC1,R1G4SA1P865EIS","HomeTheater,TV&Video",Samsung
23,B09NHVCHS9,Flix Micro Usb Cable For Smartphone (Black),Computers&Accessories,59.00,199.00,70%,4.0,"9,378","AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPYWP2OUPEYNPQ,AEBWA5I4QFCA3P3OBEPMELBGN4GQ,AHMGAC6QM62UXNEOCZIHLHSXPP2Q,AFHROSCGIXUPV3FYQ7H5QOD46Q7Q,AEAMIR3CMSA32IDEINSJKHRNANTA,AF355FTXYAKFH5NYPRTE7SL3WO3Q,AG5DWPD54QGSLWJ6QUFERLPNAX4Q","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger Planet,Justice ⚖️,indrajyoti d.,Aditya Kumar,E.C.GEORGE","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,RDVX50PD4CTFE,R3H6WKG0TA5CGU,R3Q3L1KP5QWPV3,RU0LU2PAIIME,R20FTANBPFA653",Accessories&Peripherals,Flix
24,B0B1YVCJ2Y,Acer 80 cm (32 inches) I Series HD Ready Android Smart LED TV AR32AR2841HDFL (Black),Electronics,11499.00,19990.00,42%,4.3,"4,703","AFSMISGEYDYIP3Z42UTQU4AKOYZQ,AF5ILQY4KFDTO5XHHBJ42W5DXCZQ,AFBK3X6D3AHEHSYYXPL4L6JEMSLQ,AFNB6YVNGE6IT3AWQVSIG2TJ5L3Q,AGGKMIGXUM3JRNVY7HZ3JHPJ7WTQ,AFMECPERM2GI2XQJSBWEPZKODISQ,AETPKXNOTUEX5GH7WL7XQHDR5M7Q,AERFCJ6BOMVO5YW5XM5Z2ESOIK3A","Ayush,ROHIT A.,Kedar,Haran,Santosh Ghante,KRISHNENDU,Harindra,sangamesh","R1EBS3566VCSCG,R24MB66WRPSN2A,R25UU2M1B9BO5X,R1NXW7PGVND2LE,R3OSBPH7X9AQUK,R2I8RVEPDM0IMQ,R5RES2LABIW7Q,R3A3IRV8ZWP1U9","HomeTheater,TV&Video",Acer
25,B01M4GGIVU,Tizum High Speed HDMI Cable with Ethernet | Supports 3D 4K | for All HDMI Devices Laptop Computer Gaming Console TV Set Top Box (1.5 Meter/ 5 Feet),Electronics,199.00,699.00,72%,4.2,"12,153","AGVUE2NFN2MQEOQ4PR525B2ZI5PQ,AFO4M4BQ2WS7A3LPKJY45B5C7DYQ,AG6CREU25N6P2H7RCHNIU6GGJ5BA,AHFITGJEF76CXALJZLYP6OIC4EOA,AG54MN24SX3EMMON4AMBUNL74K3Q,AF3GETWWBGMLASY2KKNNBS2VO6DQ,AHEIPXMFMVWHNPLGUXUIV5XNP2SA,AFWQRBBVJWYTYUFQHUJE63S6VXJQ","Yashpreet Singh,Abiram,Aakaash Ramchandani,Amit katoch,Avijit Basak,Anirban B.,Dass,Gopalakrishnan","R2DIHMHOPYEASB,R24RHE9B30YXWQ,R3DYXQZQA6PPHM,R2458DMQ9C2Z4F,R36C67830VNHAA,R2GE3ZI47UVVO,R1XMBPKJ1QP1Q9,R1L6PX82T6UT6P","HomeTheater,TV&Video",Tizum
26,B08B42LWKN,OnePlus 80 cm (32 inches) Y Series HD Ready LED Smart Android TV 32Y1 (Black),Electronics,14999.00,19999.00,25%,4.2,"34,899","AFUT7ANZTZYGLXU65EQ2D5OP6UMA,AGT7YYJVUC6ZHRKQHVUQZMDNLXEA,AE7OMK3IQJR2U2JZE2HQ4BKSPA6A,AGCRCU432TIF4J2EL7GBEWOIULGQ,AERQBL3BISJQVHO3RLOOA4HKZX5A,AHIWNZ2HBQAHVE4OWODM6WH4PMOQ,AH2347WTE3DZ3TIZUB5LCLZPAYEQ,AHIH3QL5XONYJWEXF7VKLFHZBDJA","ATHARVA BONDRE,Sujitkumar Thorat,Chandrasekara rajasekara reddy,J vasanth,N/A,roshan,Boopathi,Rajesh","R3COVVOP2R7Z28,R2T6WHEO2ONNDD,RUFFV2QR43OCM,R2LK4WPIHJ7WDA,R6IPR9FHZ5BOT,R3DU4LFGTAIEMN,RVHHM5FW31JN1,R1QA870NJWIODF","HomeTheater,TV&Video",OnePlus
27,B094JNXNPV,"Ambrane Unbreakable 3 in 1 Fast Charging Braided Multipurpose Cable for Speaker with 2.1 A Speed - 1.25 meter, Black",Computers&Accessories,299.00,399.00,25%,4.0,"2,766","AFYR53OTBUX2RNAKUZHUJ4RFJJNQ,AHR735YWWYFTQI5VGEEYP3DZPB6Q,AEO5NTPVZBDP7EHO2NOJ3Q6QPN3A,AF7S5C6MJ7XPJ26E3U3Z5TIWHRMA,AGY65IJP7XREWO3GUDT46474CYKA,AE2E632GMYL5U2ESNXOX5UT5D34A,AFHE44JRHYO42EGIWNM2GC75ZIJA,AEMJJHRL3DAOOLBWHIDSFW56MJWQ","Anand sarma,lokeshnist,C,SAI KIRAN,N/A,Jagdeesh singh,Kalpit Sultania,gopi","R249YCZVKYR5XD,R1GHL3EYAQ4ZMT,R1M0NVGZXK8NGO,R3O3MTC9L2VAJ5,RS2B5ERC0SV1O,RY1GC09VYZQT8,R29MVX7H69YMY5,R2M6TTXAWRQT5G",Accessories&Peripherals,Ambrane
28,B09W5XR9RT,"Duracell USB C To Lightning Apple Certified (Mfi) Braided Sync & Charge Cable For Iphone, Ipad And Ipod. Fast Charging Lightning Cable, 3.9 Feet (1.2M) - Black",Computers&Accessories,970.00,1999.00,51%,4.4,184,"AHZWJCVEIEI76H2VGMUSN5D735IQ,AH2DFUHFTG4CKQFVGZSB4JHXSAWA,AGYTSAUTXMOPROERNJPXNEB2XWNQ,AF5JWNCDVWTXOFCICR6IYNOEQENQ,AEEFM3W6RGC2KDYG5B6N7VQXR4QA,AGRT55DXEGF2EOL63HOKKKBB2KFA,AF6R7AMFHIWTMNFF6WPGFDOF7Z5A,AEGXNM3XGAHJGUJ7MIFPE7QFMJHA","N/A,Govind Gujarathi,Vihari,shalem,Tejas,RADHA krishanan,Vasudeva Govindraju,N/A","R1Y30KU04V3QF4,RK3DSUGKIZT8Z,R3BIG7J6V2JZTU,R1QI1HTJPGLS5O,R3SETXTOZ47CM4,R10SL1Q7F6CHBK,R1CBYX6RCGU739,R3PGNXSPA35NB3",Accessories&Peripherals,Duracell
29,B077Z65HSD,"boAt A400 USB Type-C to USB-A 2.0 Male Data Cable, 2 Meter (Black)",Computers&Accessories,299.00,999.00,70%,4.3,"20,850","AFA332YHUPB6I7KMME7SOFX5RKQQ,AH3LHRL5P4YAVOQQCH72G2PJFXSA,AGUUHLF34AIEIOE5KULXXVWKBCMA,AHWY6IG3PXBBJMLVFMHHKM25BVCQ,AEOKB3ECJUM6UQOBFKMEMQVVHL4A,AEYA6LQE25O2P6C7XV62XM3YV2EQ,AHMKSLALVS62JUHSHAI3FUXWDYYA,AFZIZOK5KDBOB5QCHUQRR2ZWUYKA","GHOST,N/A,A Vase,Mani Jha,Anu B,Ganesh Inguva,Prabhu,N/A","R1G4I5FLAHM16P,R1DXRMVWV2OVE8,R2BJFG3I9TAZ2P,R35RERUQG5AERU,RQVMA35UH4D2P,R2WKO9Y6VGUOOP,R1NECHJ8DC9INS,RDDDU5N0JHZS7",Accessories&Peripherals,boAt

In [215]:
# Look at how multiple IDs are stuffed into single strings
df[['Product Id', 'User Id', 'Review Id']].head(3)

,Product Id,User Id,Review Id
0,B07JW9H4J1,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBBSNLYT3ONILA,AHCTC6ULH4XB6YHDY6PCH2R772LQ,AGYHHIERNXKA6P5T7CZLXKVPT7IQ,AG4OGOFWXJZTQ2HKYIOCOY3KXF2Q,AENGU523SXMOS7JPDTW52PNNVWGQ,AEQJHCVTNINBS4FKTBGQRQTGTE5Q,AFC3FFC5PKFF5PMA52S3VCHOZ5FQ","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1KD19VHEDV0OR,R3C02RMYQMK6FC,R39GQRVBUZBWGY,R2K9EDOE15QIRJ,R3OI7YT648TL8I"
1,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBXNGXZJT525AQ,AHONIZU3ICIEHQIGQ6R2VFRSBXOQ,AFPHD2CRPDZMWMBL7WXRSVYWS5JA,AEZ346GX3HJ4O4XNRPHCNHXQURMQ,AEPSWFPNECKO34PUC7I56ITGXR6Q,AHWVEHR5DYLVFTO2KF3IZATFQSWQ,AH4QT33M55677I7ISQOAKEQWACYQ","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RYGGS0M09S3KY,R17KQRUTAN5DKS,R3AAQGS6HP2QUK,R1HDNOG6TO2CCA,R3PHKXYA5AFEOU"
2,B096MSW6CT,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQLWQOWZ4N3OA,AHTPQRIMGUD4BYR5YIHBH3CCGEFQ,AEUVWXYP5LT7PZLLZENEO2NODPBQ,AHC7MPW55DOO6WNCOQVA2VHOD26A,AFDI6FRPFBTNBG7BAEB7JDJSMKDQ,AFQKCEEEKXCOHTDG4WUN3XPPHJQQ,AHKUUFNMBZIDLSSPA4FEHIO2EC7Q","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R25X4TBMPY91LX,R27OK7G99VK0TR,R207CYDCHJJTCJ,R3PCU8XMU173BT,R1IMONDOWRNU5V"

In [218]:
#Convert comma-separated text into Python lists
for col in ['User Id','User Name','Review Id']:
    df[col] = df[col].astype(str).str.split(',')

#Filter rows where the list lengths match perfectly
valid_lengths = (df['User Id'].str.len()==df['User Name'].str.len())&\
                (df['User Id'].str.len()==df['Review Id'].str.len())
df = df[valid_lengths]
#Explode (unpivot) the lists into separate rows simultaneously
df = df.explode(['User Id', 'User Name', 'Review Id'])
#Remove duplicate Review IDs
df = df.drop_duplicates(subset=['Review Id'])

In [221]:
# Verify the unpivoted rows
df[['Product Id', 'User Id', 'Review Id']].head(50)

   Product Id                       User Id       Review Id
0  B07JW9H4J1  AG3D6O4STAQKAY2UVGEUV46KN35Q  R3HXWT0LRP0NMF
0  B07JW9H4J1  AHMY5CWJMMK5BJRBBSNLYT3ONILA  R2AJM3LFTLZHFO
0  B07JW9H4J1  AHCTC6ULH4XB6YHDY6PCH2R772LQ    R6AQJGUP6P86
0  B07JW9H4J1  AGYHHIERNXKA6P5T7CZLXKVPT7IQ  R1KD19VHEDV0OR
0  B07JW9H4J1  AG4OGOFWXJZTQ2HKYIOCOY3KXF2Q  R3C02RMYQMK6FC
0  B07JW9H4J1  AENGU523SXMOS7JPDTW52PNNVWGQ  R39GQRVBUZBWGY
0  B07JW9H4J1  AEQJHCVTNINBS4FKTBGQRQTGTE5Q  R2K9EDOE15QIRJ
0  B07JW9H4J1  AFC3FFC5PKFF5PMA52S3VCHOZ5FQ  R3OI7YT648TL8I
1  B098NS6PVG  AECPFYFQVRUWC3KGNLJIOREFP5LQ   RGIQEG07R9HS2
1  B098NS6PVG  AGYYVPDD7YG7FYNBXNGXZJT525AQ  R1SMWZQ86XIN8U
1  B098NS6PVG  AHONIZU3ICIEHQIGQ6R2VFRSBXOQ  R2J3Y1WL29GWDE
1  B098NS6PVG  AFPHD2CRPDZMWMBL7WXRSVYWS5JA   RYGGS0M09S3KY
1  B098NS6PVG  AEZ346GX3HJ4O4XNRPHCNHXQURMQ  R17KQRUTAN5DKS
1  B098NS6PVG  AEPSWFPNECKO34PUC7I56ITGXR6Q  R3AAQGS6HP2QUK
1  B098NS6PVG  AHWVEHR5DYLVFTO2KF3IZATFQSWQ  R1HDNOG6TO2CCA
1  B098NS6PVG  AH4QT33M55677I7ISQOAKEQWACYQ  R3PHKXYA5AFEOU
2  B096MSW6CT  AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA  R3J3EQQ9TZI5ZJ
2  B096MSW6CT  AESFLDV2PT363T2AQLWQOWZ4N3OA  R3E7WBGK7ID0KV
2  B096MSW6CT  AHTPQRIMGUD4BYR5YIHBH3CCGEFQ   RWU79XKQ6I1QF
2  B096MSW6CT  AEUVWXYP5LT7PZLLZENEO2NODPBQ  R25X4TBMPY91LX
2  B096MSW6CT  AHC7MPW55DOO6WNCOQVA2VHOD26A  R27OK7G99VK0TR
2  B096MSW6CT  AFDI6FRPFBTNBG7BAEB7JDJSMKDQ  R207CYDCHJJTCJ
2  B096MSW6CT  AFQKCEEEKXCOHTDG4WUN3XPPHJQQ  R3PCU8XMU173BT
2  B096MSW6CT  AHKUUFNMBZIDLSSPA4FEHIO2EC7Q  R1IMONDOWRNU5V
3  B08HDJ86NZ  AEWAZDZZJLQUYVOVGBEUKSLXHQ5A  R3EEUZKKK9J36I
3  B08HDJ86NZ  AG5HTSFRRE6NL3M5SGCUQBP7YSCA  R3HJVYCLYOY554
3  B08HDJ86NZ  AH725ST5NW2Y4JZPKUNTIJCUK2BA   REDECAZ7AMPQC
3  B08HDJ86NZ  AHV3TXIFCJPMS4D5JATCEUR266MQ  R1CLH2ULIVG5U3
3  B08HDJ86NZ  AGWIGDEMFIIUAOXYY2QATNBSUGHA  R2DMKIBGFKBD6R
3  B08HDJ86NZ  AFSTSLQUV4EVEXWKBOLEFHL2H5YQ   RC89B5IAJUTR5
3  B08HDJ86NZ  AGAKDNBHY2FKX7I4ACRGILU7QL7A  R3B3DDON5FH8DS
3  B08HDJ86NZ  AFNWJUWJRHCC6HN52KMG5AKZY37Q  R13WAEJDI5RS36
4  B08CF3B7N1  AE3Q6KSUK5P75D5HFYHCRAOLODSA  R1BP4L2HH9TFUP
4  B08CF3B7N1  AFUGIFH5ZAFXRDSZHM4QB2KPKFUQ  R16PVJEXKV6QZS
4  B08CF3B7N1  AFK4NJOLFSJGWLOJIUIAROJF6YVA  R2UPDB81N66T4P
4  B08CF3B7N1  AFUOTYRFUXVPEBGIXVZZ7DR3CZUA  R3KK4GT934ST3I
4  B08CF3B7N1  AFDLRSXKDZ6U3U3KD46SQLFGZQRA    RCFHMWUSBIJO
4  B08CF3B7N1  AH5VLM66SIK7J3IRG4NY7XVOQ55A   RDO7DACXMAJ84
4  B08CF3B7N1  AE3MQNNHHLUHXURL5S7IAR7JTGNQ  R3A6MEZL3LY66Z
4  B08CF3B7N1  AFSEOFZY67MYC7UAJU264Z5NFTLA  R1ESIEKPGAYA29
6  B08WRWPM22  AG7C6DAADCTRQJG2BRS3RIKDT52Q   R8E73K2KWJRDS
6  B08WRWPM22  AFU7BOMPVJ7Q3TTA4G67RASTGYIQ   RSD0JTIIWQQL8
6  B08WRWPM22  AER5ZGIXXVYG3AWZTRZT7M2BYCEA   R64CRSTE9SLW1
6  B08WRWPM22  AHE76XQSOLGOP5ZEKTIW6KUPDWBQ  R2FRTNIIUFJE1F
6  B08WRWPM22  AGXTMB2XHZBEWZ2UIX7ODZ4XTU6Q   RWGNX3W7UOJ7W
6  B08WRWPM22  AHNM2XVU745EDPNGUOAG74PTSNRA  R32TYHHODHTF5D
6  B08WRWPM22  AH5RWQ4S72IVLZD6O75OPCFIVDXQ   RQL9ZMQUTY7P2
6  B08WRWPM22  AG322TYKVPLPBDXE7ABEUK5QTALQ  R280XJ5VZUBOXV
7  B08DDRGWTJ  AHW6E5LQ2BDYOIVLAJGDH45J5V5Q  R2X090D1YHACKR
7  B08DDRGWTJ  AF74RSGCHPZITVFSZN76K6GKPICA  R32ZCIH9AFNJ60

In [222]:
df.to_csv('amazon-python.csv',index=False,encoding='utf-8-sig')

In [265]:
df.columns

Index(['Product Id', 'Product Name', 'Category', 'Discounted Price',
       'Actual Price', 'Discount Percentage', 'Rating', 'Rating Count',
       'User Id', 'User Name', 'Review Id', 'Sub Category', 'Brand'],
      dtype='str')

In [266]:
#Select the final columns I want for the dashboard
final_columns = [
    'Product Id', 'Product Name', 'Brand', 'Category', 'Sub Category', 
    'Discounted Price', 'Actual Price', 'Discount Percentage', 
    'Rating', 'Rating Count', 'User Id', 'User Name', 'Review Id'
]
df_final = df[final_columns].copy()
#Standardize ID column names
df_final = df_final.rename(columns={
    'Product Id': 'Product ID', 
    'User Id': 'User ID', 
    'Review Id': 'Review ID'
})

In [267]:
# Verify the final flat table is ready
print(df_final.info())

<class 'pandas.DataFrame'>
Index: 9213 entries, 0 to 1464
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product ID           9213 non-null   str
 1   Product Name         9213 non-null   str
 2   Brand                9213 non-null   object
 3   Category             9213 non-null   str
 4   Sub Category         9213 non-null   str
 5   Discounted Price     9213 non-null   float64
 6   Actual Price         9213 non-null   float64
 7   Discount Percentage  9213 non-null   str
 8   Rating               9213 non-null   str
 9   Rating Count         9211 non-null   str
 10  User ID              9213 non-null   str
 11  User Name            9213 non-null   str
 12  Review ID            9213 non-null   str
dtypes: float64(2), object(1), str(10)
memory usage: 3.1+ MB
None

In [268]:
df_final['Discount Percentage'].head(10)

0    64%
0    64%
0    64%
0    64%
0    64%
0    64%
0    64%
0    64%
1    43%
1    43%
Name: Discount Percentage, dtype: str

In [269]:
#Fix Discount Percentage (remove %, convert to decimal)
df_final['Discount Percentage'] = df_final['Discount Percentage'].str.replace('%','')
df_final['Discount Percentage'] = pd.to_numeric(df_final['Discount Percentage'])/100

In [270]:
#Verify the fix
df_final['Discount Percentage'].head(10)

0    0.64
0    0.64
0    0.64
0    0.64
0    0.64
0    0.64
0    0.64
0    0.64
1    0.43
1    0.43
Name: Discount Percentage, dtype: float64

In [271]:
#Fix Rating Count (remove commas, handle errors, fill missing with 0, convert to integer)
df_final['Rating Count'] = df_final['Rating Count'].str.replace(',', '')
df_final['Rating Count'] = pd.to_numeric(
    df_final['Rating Count'],
    errors='coerce'
).fillna(0).astype(int)

In [272]:
df_final['Rating Count'].head(10)

0    24269
0    24269
0    24269
0    24269
0    24269
0    24269
0    24269
0    24269
1    43994
1    43994
Name: Rating Count, dtype: int64

In [273]:
#Fix Rating (convert to number, forcing any weird text to NaN)
df_final['Rating'] = pd.to_numeric(df_final['Rating'],errors='coerce')

In [275]:
# Verify the final data types
print(df_final.info())

<class 'pandas.DataFrame'>
Index: 9213 entries, 0 to 1464
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product ID           9213 non-null   str
 1   Product Name         9213 non-null   str
 2   Brand                9213 non-null   object
 3   Category             9213 non-null   str
 4   Sub Category         9213 non-null   str
 5   Discounted Price     9213 non-null   float64
 6   Actual Price         9213 non-null   float64
 7   Discount Percentage  9213 non-null   float64
 8   Rating               9205 non-null   float64
 9   Rating Count         9213 non-null   int64
 10  User ID              9213 non-null   str
 11  User Name            9213 non-null   str
 12  Review ID            9213 non-null   str
dtypes: float64(4), int64(1), object(1), str(7)
memory usage: 3.0+ MB
None

In [276]:
#Spot on! `df_final.info()` 
#shows that the Rating column has 9,205 non-null values out of 9,213,
#meaning 8 rows are missing a rating.

In [278]:
# Check total missing values per column
df_final.isna().sum()

Product ID             0
Product Name           0
Brand                  0
Category               0
Sub Category           0
Discounted Price       0
Actual Price           0
Discount Percentage    0
Rating                 8
Rating Count           0
User ID                0
User Name              0
Review ID              0
dtype: int64

In [282]:
# Inspect the exact rows missing a Rating
df_final[df_final['Rating'].isna()]

,Product ID,Product Name,Brand,Category,Sub Category,Discounted Price,Actual Price,Discount Percentage,Rating,Rating Count,User ID,User Name,Review ID
1279,B08L12N5H1,"Eureka Forbes car Vac 100 Watts Powerful Suction Vacuum Cleaner with Washable HEPA Filter, 3 Accessories,Compact,Light Weight & Easy to use (Black and Red)",Eureka,Home&Kitchen,Kitchen&HomeAppliances,2099.0,2499.0,0.16,NaN,992,AGTDSNT2FKVYEPDPXAA673AIS44A,Divya,R2KKTKM4M9RDVJ
1279,B08L12N5H1,"Eureka Forbes car Vac 100 Watts Powerful Suction Vacuum Cleaner with Washable HEPA Filter, 3 Accessories,Compact,Light Weight & Easy to use (Black and Red)",Eureka,Home&Kitchen,Kitchen&HomeAppliances,2099.0,2499.0,0.16,NaN,992,AER2XFSWNN4LAUCJ55IY5SOMF7WA,Dr Nefario,R1O692MZOBTE79
1279,B08L12N5H1,"Eureka Forbes car Vac 100 Watts Powerful Suction Vacuum Cleaner with Washable HEPA Filter, 3 Accessories,Compact,Light Weight & Easy to use (Black and Red)",Eureka,Home&Kitchen,Kitchen&HomeAppliances,2099.0,2499.0,0.16,NaN,992,AE3MSW6H3AL6F3ZGR5LCN5AHJO6A,Deekshith,R2WRSEWL56SOS4
1279,B08L12N5H1,"Eureka Forbes car Vac 100 Watts Powerful Suction Vacuum Cleaner with Washable HEPA Filter, 3 Accessories,Compact,Light Weight & Easy to use (Black and Red)",Eureka,Home&Kitchen,Kitchen&HomeAppliances,2099.0,2499.0,0.16,NaN,992,AG5OL5WIIPJBY25HISJLM5K2UBTQ,Preeti,R3VZRQJOKCBSH4
1279,B08L12N5H1,"Eureka Forbes car Vac 100 Watts Powerful Suction Vacuum Cleaner with Washable HEPA Filter, 3 Accessories,Compact,Light Weight & Easy to use (Black and Red)",Eureka,Home&Kitchen,Kitchen&HomeAppliances,2099.0,2499.0,0.16,NaN,992,AGHFSIBYVYXUGSNYUDAHBGOIZ3KQ,Prasanth R,R2QI4626ASSCIT
1279,B08L12N5H1,"Eureka Forbes car Vac 100 Watts Powerful Suction Vacuum Cleaner with Washable HEPA Filter, 3 Accessories,Compact,Light Weight & Easy to use (Black and Red)",Eureka,Home&Kitchen,Kitchen&HomeAppliances,2099.0,2499.0,0.16,NaN,992,AHYH6AZT3U3U44CDW5Y563UYIIUA,Pradeep kashiram Tetgure.,R1TFFJ5ON6ATEO
1279,B08L12N5H1,"Eureka Forbes car Vac 100 Watts Powerful Suction Vacuum Cleaner with Washable HEPA Filter, 3 Accessories,Compact,Light Weight & Easy to use (Black and Red)",Eureka,Home&Kitchen,Kitchen&HomeAppliances,2099.0,2499.0,0.16,NaN,992,AFLOAOURRZZZGFBF7F6IKGXRB6NQ,Abhijin Janardhan,R14JK9VQCXXEKU
1279,B08L12N5H1,"Eureka Forbes car Vac 100 Watts Powerful Suction Vacuum Cleaner with Washable HEPA Filter, 3 Accessories,Compact,Light Weight & Easy to use (Black and Red)",Eureka,Home&Kitchen,Kitchen&HomeAppliances,2099.0,2499.0,0.16,NaN,992,AGNWBYEVAIII4MPQNKN3LFVOHYZQ,Prashant,R1V4J4B7RXHG8T

In [283]:
#Since all 8 missing rows belong to the same product (Eureka Forbes Car Vac), 
#I can either fill the missing rating with 
#the overall dataset median rating (so I don’t skew the stats) 
#or drop those rows. 
#Filling with the median is best to preserve the customer count.
#This is highly dependent on 
#the dataset, the management goals, the analysis I want to do, and the data source.

In [286]:
# Calculate median rating across the dataset
median_rating = df_final['Rating'].median()
print(median_rating)

4.1

In [287]:
#Fill missing ratings with the median
df_final['Rating'] = df_final['Rating'].fillna(median_rating)

In [290]:
# Verify no null values remain
df_final['Rating'].isna().sum()

np.int64(0)

In [293]:
print(df_final.info())

<class 'pandas.DataFrame'>
Index: 9213 entries, 0 to 1464
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product ID           9213 non-null   str
 1   Product Name         9213 non-null   str
 2   Brand                9213 non-null   object
 3   Category             9213 non-null   str
 4   Sub Category         9213 non-null   str
 5   Discounted Price     9213 non-null   float64
 6   Actual Price         9213 non-null   float64
 7   Discount Percentage  9213 non-null   float64
 8   Rating               9213 non-null   float64
 9   Rating Count         9213 non-null   int64
 10  User ID              9213 non-null   str
 11  User Name            9213 non-null   str
 12  Review ID            9213 non-null   str
dtypes: float64(4), int64(1), object(1), str(7)
memory usage: 3.0+ MB
None

In [295]:
# Convert Brand to string type
df_final['Brand'] = df_final['Brand'].astype(str)

In [298]:
df_final.dtypes

Product ID                 str
Product Name               str
Brand                      str
Category                   str
Sub Category               str
Discounted Price       float64
Actual Price           float64
Discount Percentage    float64
Rating                 float64
Rating Count             int64
User ID                    str
User Name                  str
Review ID                  str
dtype: object

In [299]:
# Check numerical bounds (min, max, mean)
print(df_final[['Discounted Price', 'Actual Price', 'Discount Percentage', 'Rating', 'Rating Count']].describe())

       Discounted Price   Actual Price  Discount Percentage       Rating  \
count       9213.000000    9213.000000          9213.000000  9213.000000
mean        2513.021596    4550.870474             0.462788     4.085325
std         5549.713960    9333.083076             0.214442     0.298883
min           39.000000      39.000000             0.000000     2.000000
25%          348.000000     845.000000             0.310000     3.900000
50%          809.000000    1690.000000             0.480000     4.100000
75%         1995.000000    3990.000000             0.620000     4.300000
max        77990.000000  139900.000000             0.940000     5.000000

        Rating Count
count    9213.000000
mean    14017.438619
std     32914.802617
min         0.000000
25%       992.000000
50%      3842.000000
75%     13120.000000
max    426973.000000

In [300]:
df_final.to_csv('amazon-python.csv',index=False,encoding='utf-8-sig')

In [301]:
#Now let's build the dashboard. I use Streamlit.

In [308]:
#When I was building the dashboard, I noticed some mistakes in the Brand column.

In [344]:
df_final['Brand'].unique()

<ArrowStringArray>
[        'Wayona',        'Ambrane',         'Sounce',           'boAt',
     'Portronics',             'MI',        'TP-Link',   'AmazonBasics',
             'LG',       'Duracell',
 ...
         'Dynore',       'LACOPINE',        'Karcher',        'Larrito',
         'Hilton',          'Syska', 'Kitchengenix's',         'KNOWZA',
            'NGI',           'Noir']
Length: 406, dtype: str

In [321]:
#I need to show all the rows.
pd.set_option('display.max_rows',None)

In [323]:
df_final['Brand'].unique()

<ArrowStringArray>
[        'Wayona',        'Ambrane',         'Sounce',           'boAt',
     'Portronics',             'MI',        'TP-Link',   'AmazonBasics',
             'LG',       'Duracell',
 ...
         'Dynore',       'LACOPINE',        'Karcher',        'Larrito',
         'Hilton',          'Syska', 'Kitchengenix's',         'KNOWZA',
            'NGI',           'Noir']
Length: 406, dtype: str

In [327]:
#It still doesn’t work. Let’s try another solution.
for brand in df_final['Brand'].unique():
    print(brand)
#Some values need to be corrected.

Wayona
Ambrane
Sounce
boAt
Portronics
MI
TP-Link
AmazonBasics
LG
Duracell
tizum
Samsung
Flix
Acer
Tizum
OnePlus
Zoul
pTron
Amazonbasics
Mi
Wecool
D-Link
7SEVEN
VW
Tata
Airtel
Lapster
Redmi
Model-P4
Amazon
oraimo
CEDO
Pinnaclz
TCL
SWAPKART
Firestick
SKYWALL
Gizga
ZEBRONICS
LOHAYA
Gilary
Dealfreez
Isoelite
VU
Croma
Cotbolt
Electvision
King
Belkin
Remote
Hisense
iFFALCON
Saifsmart
Unknown
LRIPL
Kodak
BlueRigger
GENERIC
EGate
Realme
Syncwire
Skadioo
Sony
Storite
Karbonn
Zebronics
Time
Caldipree
Universal
Amkette
POPIO
MYVN
WZATCO
Crypo
Posh
Astigo
Caprigo
TATA
Soni
Rts
Agaro
Sansui
Hi-Mobiler
Smashtronics
SVM
CableCreation
Cubetek
KRISONS
Toshiba
Lenovo
Tuarso
PROLEGEND
WANBO
Lava
Technotech
NK
LS
ZORBES
Synqe
Bestor
Irusu
Shopoflux
EYNK
LUNAGARIYA
PRUSHTI
Aine
REDTECH
ESR
Fire-Boltt
SanDisk
Noise
Nokia
JBL
PTron
ELV
iQOO
WeCool
OPPO
Tygot
STRIFF
Oraimo
Goldmedal
HP
Spigen
Motorola
KINGONE
Tecno
Tukzer
Elv
Myvn
Newly
Kyosei
OpenTech
EN
URBN
Apple
LIRAMARK
SHREENOVA
POCO
WeRun
Tokdis
LAPSTER
Prolet
Mobilife
DYAZO
Logitech
Storio
SKE
Boult
Dell
Boya
Classmate
Seagate
SYVO
Casio
DIGITEK
GIZGA
Eveready
PIDILITE
Oakter
Xiaomi
Zodo
Panasonic
MemeHo
Epson
Quantum
rts
Digitek
COI
Fujifilm
E-COSMOS
AirCase
Robustrion
Redgear
TP-link
Callas
Kanget
Infinity
Parker
Luxor
Tarkan
HUMBLE
Crucial
APC
Wembley
Dyazo
Western
Zinq
MAONO
ESnipe
BRUSTRO
Cuzor
INOVERA
TVARA
RESONATE
OFIXO
FEDUS
Kingston
ENVIE
Verilux
Anjaney
ProElite
Pentonic
Apsara
Ant
Pilot
IT2M
KLAM
CP
RPM
Wacom
Camel
SupCares
Qubo
Hp
Redragon
Silicone
Canon
Faber-Castell
SaleOn
Wings
Cablet
RC
Amazfit
Tabelito
Scarters
SLOVIC
Orico
Artis
Imou
Sennheiser
HB
Foxin
PC
Inventis
Offbeat
Camlin
CARECASE
BESTOR
Pigeon
USHA
StyleHouse
beatXP
Glun
Prestige
Bajaj
SHOPTOSHOP
Orpat
PRO365
Havells
Morphy
KENT
Lifelong
INALSA
PrettyKrafts
Philips
AGARO
NutriPro
Butterfly
SOFLIN
Orient
Bulfyss
PHILIPS
Room
Wonderchef
Crompton
Borosil
Simxen
HealthSense
VR
Eureka
Maharaja
GILTON
Milton
Kuber
IKEA
Lint
C
Luminous
Wipro
Kitchen
Ikea
HUL
Preethi
Themisto
InstaCuppa
White
SAIELLIN
Cookwell
Swiffer
Hindware
ATOM
Portable
atomberg
Usha
Reffair
Activa
V-Guard
Homeistic
Kitchenwell
SKYTONE
FABWARE
Brayden
Venus
Coway
HOMEPACK
Heart
MILTON
iBELL
Tosaa
Akiara
WIDEWINGS
Vedini
JM
Oratech
Pick
Rico
Aquasure
ROYAL
ENEM
Inalsa
VRPRIME
Eopora
FIGMENT
Balzano
Swiss
Zuvexa
ACTIVA
INDIAS
Sui
Esquire
Black+Decker
Personal
Sujata
Sure
Tesora
akiara
CSI
BAJAJ
Gadgetronics
House
Allin
Candes
MR.
Aquadpure
Melbon
Cello
Shakti
AMERICAN
Demokrazy
Instant
Livpure
ECOVACS
Kent
AVNISH
Khaitan
Nirdambhay
Proven
AO
Aquaguard
Milk
Goodscity
Solidaire
SaiEllin
Black
Longway
Singer
Racold
Green
KHAITAN
Kenstar
NEXOMS
JIALTO
Ionix
ESN
Pajaka
Saiyam
KONVIO
Raffles
IONIX
KNYUC
INKULTURE
Macmillan
TE
ZIGMA
TTK
VAPJA
Campfire
FYA
LONAXA
SUJATA
Wolpin
Abode
CARDEX
Libra
Glen
Dynore
LACOPINE
Karcher
Larrito
Hilton
Syska
Kitchengenix's
KNOWZA
NGI
Noir

In [345]:
#Strip the Brand column to remove the spaces at the beginning and the end.
df_final['Brands'] = df_final['Brand'].str.strip()

In [346]:
#Make a lowercase version of the brands
lower_map = df_final['Brand'].str.lower()
canonical = (
    df_final.groupby(lower_map)['Brand']#Group using the lowercase names
    .agg(lambda x: x.value_counts().idxmax())  # most frequent casing wins
)
df_final['Brand_clean'] = lower_map.map(canonical)#map() means "take each value 
                                            #and convert it using a rule."

In [352]:
# Identify potentially duplicate or misspelled brand names by comparing each unique brand
# with all other brands using fuzzy string matching,
#then display matches with a similarity score of 85% or higher.
uniques = df_final['Brand_clean'].unique()
suspects = []
for current_brand in uniques:
    match, score, _ = process.extractOne(
        current_brand,
        [other_brand for other_brand in uniques if other_brand != current_brand],
        scorer=fuzz.ratio
    )

    if score >= 85:
        suspects.append((current_brand, match, score))    
pd.DataFrame(suspects, columns=['brand', 'closest_match', 'score']).sort_values('score', ascending=False)

Empty DataFrame
Columns: [brand, closest_match, score]
Index: []

In [357]:
# Flag placeholder/generic values in Brand_clean and replace them with "Unlisted/Junk".
placeholder_list = ['Unknown', 'GENERIC', 'Generic', 'Remote', 'PC', 'Kitchen', 'Room',
                     'White', 'Black', 'Green', 'Silicone', 'Time', 'Universal', 'Portable',
                     'Personal', 'Instant', 'Milk', 'House', 'Heart', 'Pick', 'Swiss',
                     'Sure', 'C', 'Sui', 'TE', 'MR.']

df_final['Brand_flagged'] = df_final['Brand_clean'].isin(placeholder_list)
df_final.loc[df_final['Brand_flagged'], 'Brand_clean'] = 'Unlisted/Junk'

In [358]:
# Manually correct specific brand names with known spelling errors.
manual_fixes={
    'Soni': 'Sony',
    "Kitchengenix's": 'Kitchengenix',
}
df_final['Brand_clean'] = df_final['Brand_clean'].replace(manual_fixes)

In [406]:
# Standardize "King" brand name and verify remaining King entries
df_final['Brand_clean'] = df_final['Brand_clean'].replace('King', 'King Shine')
df_final.loc[df_final['Brand_clean'].str.lower()=='king',['Product Name','Brand_clean']]

Empty DataFrame
Columns: [Product Name, Brand_clean]
Index: []

In [407]:
df_final.to_csv('amazon-python.csv',index=False,encoding='utf-8-sig')

In [3]:
df = pd.read_csv('amazon-python.csv')

In [24]:
#Check the brand_clean column looking for any mistakes.
for brand in df['Brand_clean'].unique():
    print(brand)

Wayona
Ambrane
Sounce
boAt
Portronics
MI
TP-Link
AmazonBasics
LG
Duracell
Tizum
Samsung
Flix
Acer
OnePlus
Zoul
PTron
WeCool
D-Link
7SEVEN
VW
Tata
Airtel
Lapster
Redmi
Model-P4
Amazon
oraimo
CEDO
Pinnaclz
TCL
SWAPKART
Unlisted/Junk
SKYWALL
Gizga
Zebronics
LOHAYA
Gilary
Dealfreez
Isoelite
VU
Croma
Cotbolt
Electvision
King Shine
Belkin
Hisense
iFFALCON
Saifsmart
LRIPL
Kodak
BlueRigger
EGate
Realme
Syncwire
Skadioo
Sony
Storite
Karbonn
Caldipree
Amkette
POPIO
MYVN
WZATCO
Crypo
Posh
Astigo
Caprigo
Rts
AGARO
Sansui
Hi-Mobiler
Smashtronics
SVM
CableCreation
Cubetek
KRISONS
Toshiba
Lenovo
Tuarso
PROLEGEND
WANBO
Lava
Technotech
NK
LS
ZORBES
Synqe
Bestor
Irusu
Shopoflux
EYNK
LUNAGARIYA
PRUSHTI
Aine
REDTECH
ESR
Fire-Boltt
SanDisk
Noise
Nokia
JBL
ELV
iQOO
OPPO
Tygot
STRIFF
Goldmedal
HP
Spigen
Motorola
KINGONE
Tecno
Tukzer
Newly
Kyosei
OpenTech
EN
URBN
Apple
LIRAMARK
SHREENOVA
POCO
WeRun
Tokdis
Prolet
Mobilife
DYAZO
Logitech
Storio
SKE
Boult
Dell
Boya
Classmate
Seagate
SYVO
Casio
DIGITEK
Eveready
PIDILITE
Oakter
Xiaomi
Zodo
Panasonic
MemeHo
Epson
Quantum
COI
Fujifilm
E-COSMOS
AirCase
Robustrion
Redgear
Callas
Kanget
Infinity
Parker
Luxor
Tarkan
HUMBLE
Crucial
APC
Wembley
Western
Zinq
MAONO
ESnipe
BRUSTRO
Cuzor
INOVERA
TVARA
RESONATE
OFIXO
FEDUS
Kingston
ENVIE
Verilux
Anjaney
ProElite
Pentonic
Apsara
Ant
Pilot
IT2M
KLAM
CP
RPM
Wacom
Camel
SupCares
Qubo
Redragon
Canon
Faber-Castell
SaleOn
Wings
Cablet
RC
Amazfit
Tabelito
Scarters
SLOVIC
Orico
Artis
Imou
Sennheiser
HB
Foxin
Inventis
Offbeat
Camlin
CARECASE
Pigeon
Usha
StyleHouse
beatXP
Glun
Prestige
Bajaj
SHOPTOSHOP
Orpat
PRO365
Havells
Morphy
KENT
Lifelong
INALSA
PrettyKrafts
Philips
NutriPro
Butterfly
SOFLIN
Orient
Bulfyss
Wonderchef
Crompton
Borosil
Simxen
HealthSense
VR
Eureka
Maharaja
GILTON
Milton
Kuber
IKEA
Lint
Luminous
Wipro
HUL
Preethi
Themisto
InstaCuppa
SAIELLIN
Cookwell
Swiffer
Hindware
ATOM
atomberg
Reffair
Activa
V-Guard
Homeistic
Kitchenwell
SKYTONE
FABWARE
Brayden
Venus
Coway
HOMEPACK
iBELL
Tosaa
akiara
WIDEWINGS
Vedini
JM
Oratech
Rico
Aquasure
ROYAL
ENEM
VRPRIME
Eopora
FIGMENT
Balzano
Zuvexa
INDIAS
Esquire
Black+Decker
Sujata
Tesora
CSI
Gadgetronics
Allin
Candes
Aquadpure
Melbon
Cello
Shakti
American Micronic
Demokrazy
Livpure
ECOVACS
AVNISH
KHAITAN
Nirdambhay
Proven
AO
Aquaguard
Goodscity
Solidaire
Longway
Singer
Racold
Kenstar
NEXOMS
JIALTO
IONIX
ESN
Pajaka
Saiyam
KONVIO
Raffles
KNYUC
INKULTURE
Macmillan
ZIGMA
TTK
VAPJA
Campfire
FYA
LONAXA
Wolpin
Abode
CARDEX
Libra
Glen
Dynore
LACOPINE
Karcher
Larrito
Hilton
Syska
Kitchengenix
KNOWZA
NGI
Noir

In [29]:
df['Brand_clean']=df['Brand_clean'].replace('Model-P4','Unlisted/Junk')

In [38]:
#Make the column widths unlimited so I can see all the columns and check the values. 
#I think they might need cleaning.
pd.set_option('display.max_colwidth',None)
df.loc[df['Brand_clean'].str.contains('SWAPKART'),['Product Name','Brand_clean']]

,Product Name,Brand_clean
512,"SWAPKART Fast Charging Cable and Data Sync USB Cable Compatible for iPhone 6/6S/7/7+/8/8+/10/11, 12, 13 Pro max iPad Air/Mini, iPod and iOS Devices (White)",SWAPKART
513,"SWAPKART Fast Charging Cable and Data Sync USB Cable Compatible for iPhone 6/6S/7/7+/8/8+/10/11, 12, 13 Pro max iPad Air/Mini, iPod and iOS Devices (White)",SWAPKART
514,"SWAPKART Fast Charging Cable and Data Sync USB Cable Compatible for iPhone 6/6S/7/7+/8/8+/10/11, 12, 13 Pro max iPad Air/Mini, iPod and iOS Devices (White)",SWAPKART
515,"SWAPKART Fast Charging Cable and Data Sync USB Cable Compatible for iPhone 6/6S/7/7+/8/8+/10/11, 12, 13 Pro max iPad Air/Mini, iPod and iOS Devices (White)",SWAPKART
516,"SWAPKART Fast Charging Cable and Data Sync USB Cable Compatible for iPhone 6/6S/7/7+/8/8+/10/11, 12, 13 Pro max iPad Air/Mini, iPod and iOS Devices (White)",SWAPKART
517,"SWAPKART Fast Charging Cable and Data Sync USB Cable Compatible for iPhone 6/6S/7/7+/8/8+/10/11, 12, 13 Pro max iPad Air/Mini, iPod and iOS Devices (White)",SWAPKART
518,"SWAPKART Fast Charging Cable and Data Sync USB Cable Compatible for iPhone 6/6S/7/7+/8/8+/10/11, 12, 13 Pro max iPad Air/Mini, iPod and iOS Devices (White)",SWAPKART
519,"SWAPKART Fast Charging Cable and Data Sync USB Cable Compatible for iPhone 6/6S/7/7+/8/8+/10/11, 12, 13 Pro max iPad Air/Mini, iPod and iOS Devices (White)",SWAPKART
2522,"SWAPKART Flexible Mobile Tabletop Stand, Metal Built, Heavy Duty Foldable Lazy Bracket Clip Mount Multi Angle Clamp for All Smartphones (Pack of 1), Multi Color",SWAPKART
2523,"SWAPKART Flexible Mobile Tabletop Stand, Metal Built, Heavy Duty Foldable Lazy Bracket Clip Mount Multi Angle Clamp for All Smartphones (Pack of 1), Multi Color",SWAPKART
2524,"SWAPKART Flexible Mobile Tabletop Stand, Metal Built, Heavy Duty Foldable Lazy Bracket Clip Mount Multi Angle Clamp for All Smartphones (Pack of 1), Multi Color",SWAPKART
2525,"SWAPKART Flexible Mobile Tabletop Stand, Metal Built, Heavy Duty Foldable Lazy Bracket Clip Mount Multi Angle Clamp for All Smartphones (Pack of 1), Multi Color",SWAPKART
2526,"SWAPKART Flexible Mobile Tabletop Stand, Metal Built, Heavy Duty Foldable Lazy Bracket Clip Mount Multi Angle Clamp for All Smartphones (Pack of 1), Multi Color",SWAPKART
2527,"SWAPKART Flexible Mobile Tabletop Stand, Metal Built, Heavy Duty Foldable Lazy Bracket Clip Mount Multi Angle Clamp for All Smartphones (Pack of 1), Multi Color",SWAPKART
2528,"SWAPKART Flexible Mobile Tabletop Stand, Metal Built, Heavy Duty Foldable Lazy Bracket Clip Mount Multi Angle Clamp for All Smartphones (Pack of 1), Multi Color",SWAPKART
2529,"SWAPKART Flexible Mobile Tabletop Stand, Metal Built, Heavy Duty Foldable Lazy Bracket Clip Mount Multi Angle Clamp for All Smartphones (Pack of 1), Multi Color",SWAPKART
5744,"SWAPKART Portable Flexible Adjustable Eye Protection USB LED Desk Light Table Lamp for Reading, Working on PC, Laptop, Power Bank, Bedroom ( Multicolour )",SWAPKART
5745,"SWAPKART Portable Flexible Adjustable Eye Protection USB LED Desk Light Table Lamp for Reading, Working on PC, Laptop, Power Bank, Bedroom ( Multicolour )",SWAPKART
5746,"SWAPKART Portable Flexible Adjustable Eye Protection USB LED Desk Light Table Lamp for Reading, Working on PC, Laptop, Power Bank, Bedroom ( Multicolour )",SWAPKART
5747,"SWAPKART Portable Flexible Adjustable Eye Protection USB LED Desk Light Table Lamp for Reading, Working on PC, Laptop, Power Bank, Bedroom ( Multicolour )",SWAPKART
5748,"SWAPKART Portable Flexible Adjustable Eye Protection USB LED Desk Light Table Lamp for Reading, Working on PC, Laptop, Power Bank, Bedroom ( Multicolour )",SWAPKART
5749,"SWAPKART Portable Flexible Adjustable Eye Protection USB LED Desk Light Table Lamp for Reading, Working on PC, Laptop, Power Bank, Bedroom ( Multicolour )",SWAPKART
5750,"SWAPKART Portable Flexible Adjustable Eye Protection USB LED Desk Light Table Lamp for Reading, Working on PC, Laptop, Power Bank, Bedroom ( Multicolour )",SWAPKART
5751,"SWAPKART Portable Flexible Adjustable Eye Protection USB LED Desk Light Table Lamp for Reading, Working on PC, Laptop, Power Bank, Bedroom ( Multicolour )",SWAPKART

In [59]:
#Some fixes.
#df.loc[df['Brand_clean'].str.lower()=='rc','Brand_clean']= 'RC PRINT'
#df[df['Brand_clean']=='RC']
#df[df['Brand_clean']=='VR']
#df[df['Brand_clean']=='INDIAS']
#df[df['Brand_clean']=='EN']
#df.loc[df['Brand_clean']=='EN','Brand_clean'] = 'EN LIGNE'
#df = df.drop(columns=['Brand_flagged'])
#df = df.drop(columns=['Brand'])
#df = df.rename(columns={'Brand_clean': 'Brand'})
#df.columns
#df['Brand']
df.to_csv('amazon-python.csv',index=False,encoding='utf-8-sig')

In [61]:
df = pd.read_csv('amazon-python.csv')

In [69]:
#df.head(100)
#I want to check the discounted price to ensure it is calculated correctly.

#Calculate expected discount percentage
expected = ((df['Actual Price']-df['Discounted Price'])/df['Actual Price'])*100
# Count total rows with incorrect percentages
(df['Discount Percentage'].round(2)!=expected.round(2)).sum()

np.int64(8871)

In [74]:
#"The Discount Percentage column clearly needs to be rebuilt."


df['Discount Percentage'] = \
(((df['Actual Price'] - df['Discounted Price']) / df['Actual Price']) * 100).round(2)

In [76]:
#Calculate expected discount percentage
expected = ((df['Actual Price']-df['Discounted Price'])/df['Actual Price'])*100
# Count total rows with incorrect percentages
(df['Discount Percentage'].round(2)!=expected.round(2)).sum()

np.int64(0)

In [78]:
#Great, the Discount Percentage is now accurate.

In [81]:
#Take another look at the data.
df.head(50)

,Product ID,Product Name,Category,Sub Category,Discounted Price,Actual Price,Discount Percentage,Rating,Rating Count,User ID,User Name,Review ID,Brand
0,B07JW9H4J1,"Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)",Computers&Accessories,Accessories&Peripherals,399.00,1099.0,63.69,4.2,24269,AG3D6O4STAQKAY2UVGEUV46KN35Q,Manav,R3HXWT0LRP0NMF,Wayona
1,B07JW9H4J1,"Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)",Computers&Accessories,Accessories&Peripherals,399.00,1099.0,63.69,4.2,24269,AHMY5CWJMMK5BJRBBSNLYT3ONILA,Adarsh gupta,R2AJM3LFTLZHFO,Wayona
2,B07JW9H4J1,"Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)",Computers&Accessories,Accessories&Peripherals,399.00,1099.0,63.69,4.2,24269,AHCTC6ULH4XB6YHDY6PCH2R772LQ,Sundeep,R6AQJGUP6P86,Wayona
3,B07JW9H4J1,"Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)",Computers&Accessories,Accessories&Peripherals,399.00,1099.0,63.69,4.2,24269,AGYHHIERNXKA6P5T7CZLXKVPT7IQ,S.Sayeed Ahmed,R1KD19VHEDV0OR,Wayona
4,B07JW9H4J1,"Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)",Computers&Accessories,Accessories&Peripherals,399.00,1099.0,63.69,4.2,24269,AG4OGOFWXJZTQ2HKYIOCOY3KXF2Q,jaspreet singh,R3C02RMYQMK6FC,Wayona
5,B07JW9H4J1,"Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)",Computers&Accessories,Accessories&Peripherals,399.00,1099.0,63.69,4.2,24269,AENGU523SXMOS7JPDTW52PNNVWGQ,Khaja moin,R39GQRVBUZBWGY,Wayona
6,B07JW9H4J1,"Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)",Computers&Accessories,Accessories&Peripherals,399.00,1099.0,63.69,4.2,24269,AEQJHCVTNINBS4FKTBGQRQTGTE5Q,Anand,R2K9EDOE15QIRJ,Wayona
7,B07JW9H4J1,"Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)",Computers&Accessories,Accessories&Peripherals,399.00,1099.0,63.69,4.2,24269,AFC3FFC5PKFF5PMA52S3VCHOZ5FQ,S.ARUMUGAM,R3OI7YT648TL8I,Wayona
8,B098NS6PVG,"Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)",Computers&Accessories,Accessories&Peripherals,199.00,349.0,42.98,4.0,43994,AECPFYFQVRUWC3KGNLJIOREFP5LQ,ArdKn,RGIQEG07R9HS2,Ambrane
9,B098NS6PVG,"Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)",Computers&Accessories,Accessories&Peripherals,199.00,349.0,42.98,4.0,43994,AGYYVPDD7YG7FYNBXNGXZJT525AQ,Nirbhay kumar,R1SMWZQ86XIN8U,Ambrane
10,B098NS6PVG,"Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)",Computers&Accessories,Accessories&Peripherals,199.00,349.0,42.98,4.0,43994,AHONIZU3ICIEHQIGQ6R2VFRSBXOQ,Sagar Viswanathan,R2J3Y1WL29GWDE,Ambrane
11,B098NS6PVG,"Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)",Computers&Accessories,Accessories&Peripherals,199.00,349.0,42.98,4.0,43994,AFPHD2CRPDZMWMBL7WXRSVYWS5JA,Asp,RYGGS0M09S3KY,Ambrane
12,B098NS6PVG,"Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)",Computers&Accessories,Accessories&Peripherals,199.00,349.0,42.98,4.0,43994,AEZ346GX3HJ4O4XNRPHCNHXQURMQ,NaN,R17KQRUTAN5DKS,Ambrane
13,B098NS6PVG,"Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)",Computers&Accessories,Accessories&Peripherals,199.00,349.0,42.98,4.0,43994,AEPSWFPNECKO34PUC7I56ITGXR6Q,BharanI,R3AAQGS6HP2QUK,Ambrane
14,B098NS6PVG,"Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)",Computers&Accessories,Accessories&Peripherals,199.00,349.0,42.98,4.0,43994,AHWVEHR5DYLVFTO2KF3IZATFQSWQ,sonia,R1HDNOG6TO2CCA,Ambrane
15,B098NS6PVG,"Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)",Computers&Accessories,Accessories&Peripherals,199.00,349.0,42.98,4.0,43994,AH4QT33M55677I7ISQOAKEQWACYQ,Niam,R3PHKXYA5AFEOU,Ambrane
16,B096MSW6CT,"Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices",Computers&Accessories,Accessories&Peripherals,199.00,1899.0,89.52,3.9,7928,AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,Kunal,R3J3EQQ9TZI5ZJ,Sounce
17,B096MSW6CT,"Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices",Computers&Accessories,Accessories&Peripherals,199.00,1899.0,89.52,3.9,7928,AESFLDV2PT363T2AQLWQOWZ4N3OA,Himanshu,R3E7WBGK7ID0KV,Sounce
18,B096MSW6CT,"Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices",Computers&Accessories,Accessories&Peripherals,199.00,1899.0,89.52,3.9,7928,AHTPQRIMGUD4BYR5YIHBH3CCGEFQ,viswanath,RWU79XKQ6I1QF,Sounce
19,B096MSW6CT,"Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices",Computers&Accessories,Accessories&Peripherals,199.00,1899.0,89.52,3.9,7928,AEUVWXYP5LT7PZLLZENEO2NODPBQ,sai niharka,R25X4TBMPY91LX,Sounce
20,B096MSW6CT,"Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices",Computers&Accessories,Accessories&Peripherals,199.00,1899.0,89.52,3.9,7928,AHC7MPW55DOO6WNCOQVA2VHOD26A,saqib malik,R27OK7G99VK0TR,Sounce
21,B096MSW6CT,"Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices",Computers&Accessories,Accessories&Peripherals,199.00,1899.0,89.52,3.9,7928,AFDI6FRPFBTNBG7BAEB7JDJSMKDQ,Aashiq,R207CYDCHJJTCJ,Sounce
22,B096MSW6CT,"Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices",Computers&Accessories,Accessories&Peripherals,199.00,1899.0,89.52,3.9,7928,AFQKCEEEKXCOHTDG4WUN3XPPHJQQ,Ramu Challa,R3PCU8XMU173BT,Sounce
23,B096MSW6CT,"Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices",Computers&Accessories,Accessories&Peripherals,199.00,1899.0,89.52,3.9,7928,AHKUUFNMBZIDLSSPA4FEHIO2EC7Q,Sanjay gupta,R1IMONDOWRNU5V,Sounce
24,B08HDJ86NZ,"boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)",Computers&Accessories,Accessories&Peripherals,329.00,699.0,52.93,4.2,94363,AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,Omkar dhale,R3EEUZKKK9J36I,boAt
25,B08HDJ86NZ,"boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)",Computers&Accessories,Accessories&Peripherals,329.00,699.0,52.93,4.2,94363,AG5HTSFRRE6NL3M5SGCUQBP7YSCA,JD,R3HJVYCLYOY554,boAt
26,B08HDJ86NZ,"boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)",Computers&Accessories,Accessories&Peripherals,329.00,699.0,52.93,4.2,94363,AH725ST5NW2Y4JZPKUNTIJCUK2BA,HEMALATHA,REDECAZ7AMPQC,boAt
27,B08HDJ86NZ,"boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)",Computers&Accessories,Accessories&Peripherals,329.00,699.0,52.93,4.2,94363,AHV3TXIFCJPMS4D5JATCEUR266MQ,Ajwadh a.,R1CLH2ULIVG5U3,boAt
28,B08HDJ86NZ,"boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)",Computers&Accessories,Accessories&Peripherals,329.00,699.0,52.93,4.2,94363,AGWIGDEMFIIUAOXYY2QATNBSUGHA,amar singh chouhan,R2DMKIBGFKBD6R,boAt
29,B08HDJ86NZ,"boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)",Computers&Accessories,Accessories&Peripherals,329.00,699.0,52.93,4.2,94363,AFSTSLQUV4EVEXWKBOLEFHL2H5YQ,Ravi Siddan,RC89B5IAJUTR5,boAt
30,B08HDJ86NZ,"boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)",Computers&Accessories,Accessories&Peripherals,329.00,699.0,52.93,4.2,94363,AGAKDNBHY2FKX7I4ACRGILU7QL7A,Himanshu Goel,R3B3DDON5FH8DS,boAt
31,B08HDJ86NZ,"boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)",Computers&Accessories,Accessories&Peripherals,329.00,699.0,52.93,4.2,94363,AFNWJUWJRHCC6HN52KMG5AKZY37Q,Udaykumar,R13WAEJDI5RS36,boAt
32,B08CF3B7N1,"Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)",Computers&Accessories,Accessories&Peripherals,154.00,399.0,61.40,4.2,16905,AE3Q6KSUK5P75D5HFYHCRAOLODSA,rahuls6099,R1BP4L2HH9TFUP,Portronics
33,B08CF3B7N1,"Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)",Computers&Accessories,Accessories&Peripherals,154.00,399.0,61.40,4.2,16905,AFUGIFH5ZAFXRDSZHM4QB2KPKFUQ,Swasat Borah,R16PVJEXKV6QZS,Portronics
34,B08CF3B7N1,"Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)",Computers&Accessories,Accessories&Peripherals,154.00,399.0,61.40,4.2,16905,AFK4NJOLFSJGWLOJIUIAROJF6YVA,Ajay Wadke,R2UPDB81N66T4P,Portronics
35,B08CF3B7N1,"Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)",Computers&Accessories,Accessories&Peripherals,154.00,399.0,61.40,4.2,16905,AFUOTYRFUXVPEBGIXVZZ7DR3CZUA,Pranali,R3KK4GT934ST3I,Portronics
36,B08CF3B7N1,"Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)",Computers&Accessories,Accessories&Peripherals,154.00,399.0,61.40,4.2,16905,AFDLRSXKDZ6U3U3KD46SQLFGZQRA,RVK,RCFHMWUSBIJO,Portronics
37,B08CF3B7N1,"Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)",Computers&Accessories,Accessories&Peripherals,154.00,399.0,61.40,4.2,16905,AH5VLM66SIK7J3IRG4NY7XVOQ55A,Bhargav,RDO7DACXMAJ84,Portronics
38,B08CF3B7N1,"Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)",Computers&Accessories,Accessories&Peripherals,154.00,399.0,61.40,4.2,16905,AE3MQNNHHLUHXURL5S7IAR7JTGNQ,Durai Vignesh,R3A6MEZL3LY66Z,Portronics
39,B08CF3B7N1,"Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)",Computers&Accessories,Accessories&Peripherals,154.00,399.0,61.40,4.2,16905,AFSEOFZY67MYC7UAJU264Z5NFTLA,NaN,R1ESIEKPGAYA29,Portronics
40,B08WRWPM22,"boAt Micro USB 55 Tangle-free, Sturdy Micro USB Cable with 3A Fast Charging & 480mbps Data Transmission (Black)",Computers&Accessories,Accessories&Peripherals,176.63,499.0,64.60,4.1,15188,AG7C6DAADCTRQJG2BRS3RIKDT52Q,Vivek kumar,R8E73K2KWJRDS,boAt
41,B08WRWPM22,"boAt Micro USB 55 Tangle-free, Sturdy Micro USB Cable with 3A Fast Charging & 480mbps Data Transmission (Black)",Computers&Accessories,Accessories&Peripherals,176.63,499.0,64.60,4.1,15188,AFU7BOMPVJ7Q3TTA4G67RASTGYIQ,NaN,RSD0JTIIWQQL8,boAt
42,B08WRWPM22,"boAt Micro USB 55 Tangle-free, Sturdy Micro USB Cable with 3A Fast Charging & 480mbps Data Transmission (Black)",Computers&Accessories,Accessories&Peripherals,176.63,499.0,64.60,4.1,15188,AER5ZGIXXVYG3AWZTRZT7M2BYCEA,SARTHAK,R64CRSTE9SLW1,boAt
43,B08WRWPM22,"boAt Micro USB 55 Tangle-free, Sturdy Micro USB Cable with 3A Fast Charging & 480mbps Data Transmission (Black)",Computers&Accessories,Accessories&Peripherals,176.63,499.0,64.60,4.1,15188,AHE76XQSOLGOP5ZEKTIW6KUPDWBQ,Chiranjeevi,R2FRTNIIUFJE1F,boAt
44,B08WRWPM22,"boAt Micro USB 55 Tangle-free, Sturdy Micro USB Cable with 3A Fast Charging & 480mbps Data Transmission (Black)",Computers&Accessories,Accessories&Peripherals,176.63,499.0,64.60,4.1,15188,AGXTMB2XHZBEWZ2UIX7ODZ4XTU6Q,V V GIRI KUMAR,RWGNX3W7UOJ7W,boAt
45,B08WRWPM22,"boAt Micro USB 55 Tangle-free, Sturdy Micro USB Cable with 3A Fast Charging & 480mbps Data Transmission (Black)",Computers&Accessories,Accessories&Peripherals,176.63,499.0,64.60,4.1,15188,AHNM2XVU745EDPNGUOAG74PTSNRA,Rajnandini,R32TYHHODHTF5D,boAt
46,B08WRWPM22,"boAt Micro USB 55 Tangle-free, Sturdy Micro USB Cable with 3A Fast Charging & 480mbps Data Transmission (Black)",Computers&Accessories,Accessories&Peripherals,176.63,499.0,64.60,4.1,15188,AH5RWQ4S72IVLZD6O75OPCFIVDXQ,Akshay Talla,RQL9ZMQUTY7P2,boAt
47,B08WRWPM22,"boAt Micro USB 55 Tangle-free, Sturdy Micro USB Cable with 3A Fast Charging & 480mbps Data Transmission (Black)",Computers&Accessories,Accessories&Peripherals,176.63,499.0,64.60,4.1,15188,AG322TYKVPLPBDXE7ABEUK5QTALQ,sudhanshu chaubey,R280XJ5VZUBOXV,boAt
48,B08DDRGWTJ,MI Usb Type-C Cable Smartphone (Black),Computers&Accessories,Accessories&Peripherals,229.00,299.0,23.41,4.3,30411,AHW6E5LQ2BDYOIVLAJGDH45J5V5Q,Pavan A H,R2X090D1YHACKR,MI
49,B08DDRGWTJ,MI Usb Type-C Cable Smartphone (Black),Computers&Accessories,Accessories&Peripherals,229.00,299.0,23.41,4.3,30411,AF74RSGCHPZITVFSZN76K6GKPICA,Jayesh bagad,R32ZCIH9AFNJ60,MI

In [83]:
df.to_csv('amazon-python.csv',index=False,encoding='utf-8-sig')

In [84]:
#I think the data is clean—not perfect, 
#but it will be great for the project's purpose
#and the analysis that will be done on it.